/**
 * SyberMem OpenCode Plugin (generated bundle)
 * Source: packages/opencode-plugin/src/index.ts
 * Regenerate with: bun scripts/build-opencode-plugin.mjs
 * Do not edit this file by hand; installers copy this single file to ~/.config/opencode/plugins/sybermem.ts.
 */
// @bun
// packages/opencode-plugin/src/followup.ts
import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
var SKIP_PREFIXES = [".git/", ".sybermem/", "ADR/", ".claude/", ".opencode/", "node_modules/"];
var SOFT_SKIP = new Set(["CLAUDE.md", "AGENTS.md"]);
var HIGH_SIGNAL_PATTERNS = [/^README(?:\..+)?$/i, /^INSTALL(?:\..+)?$/i, /^CLAUDE\.md$/i, /^AGENTS\.md$/i, /^packages\/claude-skills\/.+\/SKILL\.md$/i, /^\.sybermem\/hooks\//i, /^scripts\/install/i, /^scripts\/update/i, /^docs\/superpowers\/specs\//i];
var HIGH_LEVEL_AREAS = [["skills", /^packages\/claude-skills\//i], ["scripts", /^scripts\//i], ["docs", /^(docs\/|README|INSTALL)/i], ["instructions", /^(CLAUDE\.md|AGENTS\.md)$/i], ["sybermem", /^\.sybermem\//i]];
var RECORD_FILE_THRESHOLD = 5;
var COMMIT_GAP_THRESHOLD = 5;
var THEME_WINDOW_SIZE = 10;
var DIGEST_CLUSTER_THRESHOLD = 2;
var DIGEST_SIGNAL_FILE_FLOOR = 3;
function activityTriggerReason(activity) {
  if (!activity)
    return null;
  if (activity.toolSignal === "tests_passed")
    return "tests_passed";
  if (activity.toolSignal === "build_ok")
    return "build_ok";
  if (activity.todoCompletedBatches > 0)
    return "todo_batch_done";
  if (activity.editFocus)
    return "edit_focus";
  return null;
}
async function getChangedFiles($, cwd) {
  const files = new Set;
  try {
    for (const output of [await $`git diff --name-only`.cwd(cwd).text(), await $`git diff --cached --name-only`.cwd(cwd).text(), await $`git ls-files --others --exclude-standard`.cwd(cwd).text()]) {
      for (const line of output.split(`
`)) {
        const f = line.trim().replace(/\\/g, "/");
        if (f && !SKIP_PREFIXES.some((p) => f.startsWith(p)))
          files.add(f);
      }
    }
  } catch {}
  return [...files];
}
function trailFiles(files) {
  return files.filter((f) => !SOFT_SKIP.has(f)).length > 0 ? [...files] : [];
}
function matchesHighSignal(file) {
  return HIGH_SIGNAL_PATTERNS.some((p) => p.test(file));
}
function detectHighLevelAreas(files) {
  const areas = new Set;
  for (const file of files)
    for (const [name, pattern] of HIGH_LEVEL_AREAS)
      if (pattern.test(file))
        areas.add(name);
  return areas;
}
function slugifyAreas(areas) {
  return [...areas].sort().join("-") || "misc";
}
function classifyFollowup(files, commitsSinceRecord, state, activity) {
  const highSignal = files.filter(matchesHighSignal);
  const areas = detectHighLevelAreas(files);
  const themeKey = slugifyAreas(areas);
  const recentStops = state.theme_recent_stops?.[themeKey] ?? [];
  const presentQualifies = highSignal.length > 0 || areas.size >= 2 || files.length >= DIGEST_SIGNAL_FILE_FLOOR;
  const nudgedAt = state.digest_nudged_at_window_len?.[themeKey];
  if (recentStops.length >= DIGEST_CLUSTER_THRESHOLD && presentQualifies && !(nudgedAt !== undefined && recentStops.length <= nudgedAt)) {
    return { type: "digest", themeKey, message: "SyberMem: recent records around this area may now be enough for a /sybermem-digest if this phase has reached a stable stopping point.", triggerReason: "digest_cluster" };
  }
  const activityReason = activityTriggerReason(activity);
  const shouldRecord = activityReason !== null || highSignal.length > 0 || areas.size >= 2 || files.length >= RECORD_FILE_THRESHOLD || commitsSinceRecord >= COMMIT_GAP_THRESHOLD;
  if (shouldRecord && !(state.last_nudge_type === "record" && state.last_theme === themeKey)) {
    const gapNote = commitsSinceRecord >= COMMIT_GAP_THRESHOLD ? ` (${commitsSinceRecord} commits since last record)` : "";
    const reason = activityReason ?? (highSignal.length > 0 || areas.size >= 2 ? "high_signal_files" : commitsSinceRecord >= COMMIT_GAP_THRESHOLD ? "commit_gap" : "file_count");
    const stopNote = describeActivity(activity, activityReason);
    return { type: "record", themeKey, message: `SyberMem: this change looks important enough for a manual /sybermem-record so the reason and impact are preserved.${stopNote}${gapNote}`, triggerReason: reason };
  }
  return { type: "none", themeKey, message: null, triggerReason: "none" };
}
function describeActivity(activity, reason) {
  if (!activity || reason === null)
    return "";
  if (reason === "tests_passed")
    return " (tests passed this session)";
  if (reason === "build_ok")
    return " (build succeeded this session)";
  if (reason === "todo_batch_done")
    return " (a batch of tasks just completed)";
  if (reason === "edit_focus" && activity.editFocus)
    return ` (focused edits on ${activity.editFocus})`;
  return "";
}
async function countCommitsSinceLastRecord($, root) {
  try {
    let latestDate = "";
    for (const subdir of ["changes", "decisions", "requirements", "bugs"]) {
      const dir = join(root, ".sybermem", subdir);
      if (!existsSync(dir))
        continue;
      const lastFile = readdirSync(dir).filter((f) => f.endsWith(".md")).sort().at(-1);
      const dateMatch = lastFile?.match(/^(\d{4}-\d{2}-\d{2})/);
      if (dateMatch && dateMatch[1] > latestDate)
        latestDate = dateMatch[1];
    }
    if (!latestDate)
      return 0;
    return (await $`git log --oneline --since=${latestDate}`.cwd(root).text()).split(`
`).filter((l) => l.trim()).length;
  } catch {
    return 0;
  }
}
function parseAutoTrailEntry(raw) {
  const parsed = JSON.parse(raw);
  if (typeof parsed !== "object" || parsed === null)
    return null;
  const files = Reflect.get(parsed, "files");
  return Array.isArray(files) ? { files: files.map(String) } : {};
}
function overlapsRecentAutoTrails(root, files) {
  const current = new Set(files);
  if (current.size === 0)
    return false;
  const p = join(root, ".sybermem", ".auto-trail.jsonl");
  const lines = existsSync(p) ? readFileSync(p, "utf-8").split(`
`).filter((line) => line.trim()).slice(-3) : [];
  for (const line of lines) {
    try {
      const entry = parseAutoTrailEntry(line);
      if (!entry)
        continue;
      const trail = new Set((entry.files ?? []).map((f) => String(f).trim()).filter(Boolean));
      let shared = 0;
      for (const f of current)
        if (trail.has(f))
          shared++;
      if (trail.size > 0 && shared / Math.max(current.size, trail.size) >= 0.8)
        return true;
    } catch {}
  }
  return false;
}
function appendAutoTrailJournal(root, date, files, areas, followupHint) {
  const p = join(root, ".sybermem", ".auto-trail.jsonl");
  try {
    const existing = existsSync(p) ? readFileSync(p, "utf-8").split(`
`).filter((l) => l.trim()) : [];
    existing.push(JSON.stringify({ date, files: [...files], areas: [...areas].sort(), followup_hint: followupHint }));
    writeFileSync(p, existing.slice(-200).join(`
`) + `
`, "utf-8");
  } catch {}
}

// packages/opencode-plugin/src/runtime.ts
import { existsSync as existsSync2 } from "fs";
import { join as join2, resolve } from "path";
function resolveRoot(cwd) {
  let current = resolve(cwd);
  while (true) {
    const hasSybermem = existsSync2(join2(current, ".sybermem"));
    const hasSettings = existsSync2(join2(current, ".claude", "settings.json"));
    const hasIndex = existsSync2(join2(current, ".sybermem", "INDEX.md"));
    if (hasSybermem && (hasSettings || hasIndex))
      return current;
    const parent = resolve(current, "..");
    if (parent === current)
      break;
    current = parent;
  }
  return null;
}
function userHome() {
  return process.env.USERPROFILE ?? process.env.HOME ?? null;
}
function resolveSybermemCommand() {
  const home = userHome();
  if (!home)
    return "sybermem";
  const launcher = process.platform === "win32" ? join2(home, ".claude", "sybermem", "cli", "sybermem.cmd") : join2(home, ".claude", "sybermem", "cli", "sybermem");
  return existsSync2(launcher) ? launcher : "sybermem";
}
async function sybermemText($, root, args) {
  const sybermem = resolveSybermemCommand();
  switch (args[0]) {
    case "next-step":
      return $`${sybermem} next-step ${args[1]} ${args[2]}`.cwd(root).text();
    case "habit":
      if (args[1] === "intent")
        return $`${sybermem} habit intent --prompt=${args[3]} --format json`.cwd(root).nothrow().text();
      if (args[1] === "awareness")
        return $`${sybermem} habit awareness --format json`.cwd(root).nothrow().text();
      return $`${sybermem} habit inject ${args[2]} ${args[3]} ${args[4]} ${args[5]}`.cwd(root).text();
    case "context":
      switch (args[1]) {
        case "session":
          return $`${sybermem} context session ${args[2]} ${args[3]}`.cwd(root).text();
        case "recall":
          return $`${sybermem} context recall --query ${args[3]} --format markdown`.cwd(root).text();
        case "habit":
          return $`${sybermem} context habit --context ${args[3]} --delivery ${args[5]} --format ${args[7]}`.cwd(root).text();
      }
      break;
    case "record":
      return $`${sybermem} record intent --prompt ${args[3]} --format ${args[5]}`.cwd(root).text();
  }
  return "";
}
async function digestStatusText($, root) {
  const sybermem = resolveSybermemCommand();
  return $`${sybermem} digest status --format json`.cwd(root).nothrow().text();
}
async function digestLatestText($, root) {
  const sybermem = resolveSybermemCommand();
  return $`${sybermem} digest latest --format json`.cwd(root).nothrow().text();
}
async function normsListText($, root, scope, context) {
  const sybermem = resolveSybermemCommand();
  return $`${sybermem} norms list --scope ${scope} --context ${context} --format json`.cwd(root).nothrow().text();
}
async function memoryStatsText($, root) {
  const sybermem = resolveSybermemCommand();
  return $`${sybermem} project memory-stats --format json`.cwd(root).nothrow().text();
}
async function recordFilesText($, root, ids) {
  const sybermem = resolveSybermemCommand();
  return $`${sybermem} project record-files --ids ${ids} --format json`.cwd(root).nothrow().text();
}

// packages/opencode-plugin/src/project_state.ts
import { existsSync as existsSync3, readFileSync as readFileSync2 } from "fs";
import { join as join3 } from "path";
function parseIndex(root) {
  const indexPath = join3(root, ".sybermem", "INDEX.md");
  if (!existsSync3(indexPath))
    return null;
  const content = readFileSync2(indexPath, "utf-8");
  const conclusionsMatch = content.match(/## Key Conclusions\s*\n([\s\S]*?)(?=\n---|\n## )/);
  const conclusions = [];
  if (conclusionsMatch) {
    for (const line of conclusionsMatch[1].split(`
`)) {
      const trimmed = line.trim();
      if (trimmed.startsWith("- ["))
        conclusions.push(trimmed);
    }
  }
  const topicMatch = content.match(/## Topic Index\s*\n([\s\S]*?)(?=\n---|\n## |$)/);
  const topicIndex = {};
  if (topicMatch) {
    for (const line of topicMatch[1].split(`
`)) {
      const m = line.match(/^- (\S+):\s*(.+)/);
      if (m)
        topicIndex[m[1]] = m[2].split(",").map((s) => s.trim());
    }
  }
  return { conclusions, topicIndex };
}
function getActivePhase(root) {
  const phasePath = join3(root, ".sybermem", "analysis", "phase-index.md");
  if (!existsSync3(phasePath))
    return null;
  const phases = [...readFileSync2(phasePath, "utf-8").matchAll(/### Phase: (.+)/g)];
  return phases.length === 0 ? null : phases[phases.length - 1][1];
}
function parsePhaseIndex(root) {
  const phasePath = join3(root, ".sybermem", "analysis", "phase-index.md");
  if (!existsSync3(phasePath))
    return { exists: false };
  const content = readFileSync2(phasePath, "utf-8");
  const statusMatch = content.match(/^- status:\s*(.+)/m);
  const phases = [...content.matchAll(/### Phase: (.+)/g)];
  return { exists: true, status: statusMatch ? statusMatch[1].trim() : "unknown", confirmedCount: phases.length, activePhase: getActivePhase(root) };
}
function parseProjectIdentity(root) {
  const projPath = join3(root, ".sybermem", "project.yaml");
  if (!existsSync3(projPath))
    return { exists: false };
  let projectId = null;
  let slug = null;
  for (const raw of readFileSync2(projPath, "utf-8").split(`
`)) {
    const line = raw.trim();
    if (line.startsWith("project_id:"))
      projectId = line.split(":").slice(1).join(":").trim();
    else if (line.startsWith("slug:"))
      slug = line.split(":").slice(1).join(":").trim();
  }
  return { exists: true, projectId, slug };
}
async function detectStaleSignal($, root) {
  const phasePath = join3(root, ".sybermem", "analysis", "phase-index.md");
  if (!existsSync3(phasePath))
    return { stale: false, commitsAhead: 0 };
  const boundaryMatch = readFileSync2(phasePath, "utf-8").match(/^- last_git_boundary:\s*(\S+)/m);
  if (!boundaryMatch)
    return { stale: false, commitsAhead: 0 };
  const boundary = boundaryMatch[1];
  try {
    const head = (await $`git rev-parse HEAD`.cwd(root).text()).trim();
    if (head === boundary)
      return { stale: false, commitsAhead: 0 };
    const countStr = (await $`git rev-list --count ${boundary}..HEAD`.cwd(root).text()).trim();
    const count = Number.parseInt(countStr, 10) || 0;
    return { stale: count >= 3, commitsAhead: count, boundary, head: head.substring(0, 7) };
  } catch {
    return { stale: false, commitsAhead: 0 };
  }
}

// packages/opencode-plugin/src/norm_signal.ts
function parseNorms(json) {
  const trimmed = json.trim();
  if (!trimmed)
    return [];
  try {
    const parsed = JSON.parse(trimmed);
    if (typeof parsed !== "object" || parsed === null)
      return [];
    const norms = Reflect.get(parsed, "norms");
    if (!Array.isArray(norms))
      return [];
    const out = [];
    for (const raw of norms) {
      if (typeof raw !== "object" || raw === null)
        continue;
      const recordId = Reflect.get(raw, "record_id");
      const statement = Reflect.get(raw, "statement");
      const scope = Reflect.get(raw, "scope");
      if (typeof recordId === "string" && typeof statement === "string" && statement) {
        out.push({ recordId, statement, scope: typeof scope === "string" ? scope : "" });
      }
    }
    return out;
  } catch {
    return [];
  }
}
function constitutionSection(norms) {
  if (norms.length === 0)
    return "";
  const lines = [`
### Project Norms (binding)`];
  for (const norm of norms)
    lines.push(`- [${norm.recordId}] ${norm.statement}`);
  lines.push("These are binding project norms \u2014 follow them unless the user explicitly overrides.");
  return lines.join(`
`) + `
`;
}
function scopedNormSection(norms) {
  if (norms.length === 0)
    return "";
  const lines = [`
### Relevant Project Norms`];
  for (const norm of norms)
    lines.push(`- [${norm.recordId}] (${norm.scope || "scoped"}) ${norm.statement}`);
  return lines.join(`
`) + `
`;
}

// packages/opencode-plugin/src/compaction.ts
async function constitutionBlock($, root) {
  try {
    return constitutionSection(parseNorms(await normsListText($, root, "global", "")));
  } catch {
    return "";
  }
}
async function latestDigestSection($, root) {
  try {
    const parsed = JSON.parse(await digestLatestText($, root));
    if (typeof parsed !== "object" || parsed === null)
      return "";
    const conclusions = Reflect.get(parsed, "conclusions");
    if (!Array.isArray(conclusions) || conclusions.length === 0)
      return "";
    const title = typeof Reflect.get(parsed, "title") === "string" ? Reflect.get(parsed, "title") : "";
    const lines = conclusions.filter((c) => typeof c === "string").slice(0, 5);
    if (lines.length === 0)
      return "";
    return `
### Latest Digest${title ? `: ${title}` : ""}
${lines.join(`
`)}
`;
  } catch {
    return "";
  }
}
function numberField(value, key) {
  if (typeof value !== "object" || value === null)
    return null;
  const field = Reflect.get(value, key);
  return typeof field === "number" ? field : null;
}
function stringField(value, key) {
  if (typeof value !== "object" || value === null)
    return "";
  const field = Reflect.get(value, key);
  return typeof field === "string" ? field.trim() : "";
}
async function buildCompactionContext($, root) {
  const parsed = parseIndex(root);
  const conclusions = parsed?.conclusions ?? [];
  const digestSection = await latestDigestSection($, root);
  const constitution = await constitutionBlock($, root);
  if (conclusions.length === 0 && !digestSection && !constitution)
    return null;
  const phaseInfo = parsePhaseIndex(root);
  const identity = parseProjectIdentity(root);
  const stale = await detectStaleSignal($, root);
  let context = "";
  try {
    const manualContext = (await sybermemText($, root, ["context", "session", "--format", "markdown"])).trim();
    if (manualContext.startsWith("## SyberMem Manual Session Context"))
      context += `${manualContext}

`;
  } catch {}
  if (!context)
    context = `## SyberMem Project Memory

`;
  if (identity.exists && identity.slug)
    context += `Project: ${identity.slug} (${identity.projectId ?? "no id"}).

`;
  context += constitution;
  if (conclusions.length > 0) {
    context += `### Key Conclusions
`;
    for (const c of conclusions)
      context += `${c}
`;
  }
  context += digestSection;
  if (stale.stale)
    context += `
\u2B50 Heads-up: phase index trails HEAD by ${stale.commitsAhead} commits \u2014 the conclusions above may lag your latest work. Consider /sybermem-phase-analyze before relying on phase context.
`;
  try {
    const staleDigestCount = numberField(JSON.parse(await digestStatusText($, root)), "stale");
    if (staleDigestCount !== null && staleDigestCount > 0)
      context += `
\u2B50 Digest heads-up: ${staleDigestCount} digest(s) are stale \u2014 their source records changed. Run /sybermem-digest to regenerate, or \`sybermem digest status\` to see which sources drifted.
`;
  } catch {}
  if (phaseInfo.exists) {
    context += `
### Phase Index
Status: ${phaseInfo.status}. ${phaseInfo.confirmedCount} confirmed phases.
`;
    if (phaseInfo.activePhase)
      context += `Active phase: ${phaseInfo.activePhase}.
`;
  }
  if (stale.stale)
    context += `
### Stale Signal
Phase-index last git boundary: ${stale.boundary}, current HEAD: ${stale.head} (${stale.commitsAhead} commits ahead).
`;
  const topicIndex = parsed?.topicIndex ?? {};
  if (Object.keys(topicIndex).length > 0) {
    context += `
### Topic Index
`;
    for (const [topic, records] of Object.entries(topicIndex))
      context += `- ${topic}: ${records.join(", ")}
`;
  }
  try {
    const rec = JSON.parse(await sybermemText($, root, ["next-step", "--format", "json"]));
    const action = stringField(rec, "action");
    const reason = stringField(rec, "reason");
    if (action)
      context += `
### Recommended Next Step
${action}${reason ? ` \u2014 ${reason}` : ""}
`;
  } catch {}
  try {
    const habitContext = "compaction planning review implementation coding documentation";
    const habitMarkdown = (await sybermemText($, root, ["habit", "inject", "--context", habitContext, "--format", "markdown"])).trim();
    if (habitMarkdown)
      context += `
${habitMarkdown}
`;
  } catch {}
  context += `
### SyberMem Commands
- /sybermem-record \u2014 create a record after meaningful work
- /sybermem-summary \u2014 view current phase status
- /sybermem-digest \u2014 create durable phase digest
`;
  return context.length > 3000 ? `${context.substring(0, 2997)}...` : context;
}

// packages/opencode-plugin/src/digest_backlog_signal.ts
function parseDigestBacklog(json) {
  const trimmed = json.trim();
  if (!trimmed)
    return null;
  try {
    const parsed = JSON.parse(trimmed);
    if (typeof parsed !== "object" || parsed === null)
      return null;
    const backlog = Reflect.get(parsed, "backlog");
    if (typeof backlog !== "object" || backlog === null)
      return null;
    const uncovered = Reflect.get(backlog, "uncovered");
    if (typeof uncovered !== "number")
      return null;
    const days = Reflect.get(backlog, "days_since_latest_digest");
    const hasDigest = Reflect.get(backlog, "has_digest");
    return {
      uncovered,
      daysSinceLatestDigest: typeof days === "number" ? days : 0,
      hasDigest: hasDigest === true
    };
  } catch {
    return null;
  }
}
var DIGEST_BACKLOG_THRESHOLD = 5;
function digestBacklogToast(backlog) {
  if (backlog.uncovered < DIGEST_BACKLOG_THRESHOLD)
    return null;
  const ageNote = backlog.hasDigest && backlog.daysSinceLatestDigest > 0 ? `\uFF08\u8DDD\u4E0A\u6B21 digest ${backlog.daysSinceLatestDigest} \u5929\uFF09` : "";
  return `\u2B50 SyberMem: ${backlog.uncovered} \u6761\u8BB0\u5F55\u5C1A\u672A\u8FDB\u5165\u4EFB\u4F55 digest${ageNote} \u2014 \u8003\u8651 /sybermem-digest \u538B\u7F29\u8FD9\u6279\u5DE5\u4F5C`;
}

// packages/opencode-plugin/src/state.ts
import { appendFileSync, existsSync as existsSync4, lstatSync, readFileSync as readFileSync3, realpathSync, statSync, writeFileSync as writeFileSync2 } from "fs";
import { join as join4, relative } from "path";
function isObject(value) {
  return typeof value === "object" && value !== null;
}
function parseNudgeState(raw) {
  const parsed = JSON.parse(raw);
  if (!isObject(parsed))
    return {};
  const lastNudge = isObject(parsed.last_nudge) ? parsed.last_nudge : null;
  const state = {};
  if (typeof parsed.lastFingerprint === "string")
    state.lastFingerprint = parsed.lastFingerprint;
  if (typeof parsed.lastNudgeCommitCount === "number")
    state.lastNudgeCommitCount = parsed.lastNudgeCommitCount;
  if (lastNudge && typeof lastNudge.platform === "string" && typeof lastNudge.type === "string" && typeof lastNudge.theme === "string" && typeof lastNudge.date === "string")
    state.last_nudge = { platform: lastNudge.platform, type: lastNudge.type, theme: lastNudge.theme, date: lastNudge.date };
  if (isObject(parsed.theme_recent_stops))
    state.theme_recent_stops = parseStringArrayMap(parsed.theme_recent_stops);
  if (isObject(parsed.digest_nudged_at_window_len))
    state.digest_nudged_at_window_len = parseNumberMap(parsed.digest_nudged_at_window_len);
  if (typeof parsed.last_theme === "string")
    state.last_theme = parsed.last_theme;
  if (typeof parsed.last_nudge_type === "string")
    state.last_nudge_type = parsed.last_nudge_type;
  return state;
}
function parseStringArrayMap(raw) {
  const parsed = {};
  for (const [key, value] of Object.entries(raw))
    if (Array.isArray(value))
      parsed[key] = value.filter((item) => typeof item === "string");
  return parsed;
}
function parseNumberMap(raw) {
  const parsed = {};
  for (const [key, value] of Object.entries(raw))
    if (typeof value === "number")
      parsed[key] = value;
  return parsed;
}
var NUDGE_STATE_FILE = ".nudge-state.json";
var LEGACY_NUDGE_STATE_FILE = ".opencode-nudge-state.json";
var MAX_EXISTING_JSONL_BYTES = 1e6;
var MAX_JSONL_ENTRY_BYTES = 16384;
function isInside(parent, child) {
  const rel = relative(parent, child);
  return rel === "" || !rel.startsWith("..") && !rel.includes(":");
}
function safeJsonlPath(root, fileName) {
  if (fileName.includes("/") || fileName.includes("\\") || !fileName.endsWith(".jsonl"))
    return null;
  const memoryDir = join4(root, ".sybermem");
  const p = join4(memoryDir, fileName);
  try {
    const dirStat = lstatSync(memoryDir);
    if (!dirStat.isDirectory() || dirStat.isSymbolicLink())
      return null;
    const realDir = realpathSync(memoryDir);
    if (existsSync4(p)) {
      const fileStat = lstatSync(p);
      if (!fileStat.isFile() || fileStat.isSymbolicLink())
        return null;
      if (!isInside(realDir, realpathSync(p)))
        return null;
    }
    return p;
  } catch {
    return null;
  }
}
function loadNudgeState(root) {
  const p = join4(root, ".sybermem", NUDGE_STATE_FILE);
  if (existsSync4(p)) {
    try {
      return parseNudgeState(readFileSync3(p, "utf-8"));
    } catch {}
  }
  const legacy = join4(root, ".sybermem", LEGACY_NUDGE_STATE_FILE);
  if (existsSync4(legacy)) {
    try {
      const data = parseNudgeState(readFileSync3(legacy, "utf-8"));
      saveNudgeState(root, data);
      return data;
    } catch {}
  }
  return {};
}
function saveNudgeState(root, state) {
  writeFileSync2(join4(root, ".sybermem", NUDGE_STATE_FILE), JSON.stringify(state, null, 2) + `
`, "utf-8");
}
function boundedJsonlAppend(root, fileName, entry, limit) {
  try {
    const p = safeJsonlPath(root, fileName);
    if (!p)
      return;
    const line = JSON.stringify(entry);
    if (Buffer.byteLength(line, "utf-8") > MAX_JSONL_ENTRY_BYTES)
      return;
    appendFileSync(p, `${line}
`, "utf-8");
  } catch {}
}
function compactJsonlJournal(root, fileName, limit) {
  try {
    const p = safeJsonlPath(root, fileName);
    if (!p || limit <= 0 || statSync(p).size > MAX_EXISTING_JSONL_BYTES)
      return;
    const existing = readFileSync3(p, "utf-8").split(`
`).filter((line) => line.trim());
    writeFileSync2(p, existing.slice(-limit).join(`
`) + `
`, "utf-8");
  } catch {}
}

// packages/opencode-plugin/src/recall_debug.ts
var RECORD_ID_RE = /\b(?:change|decision|requirement|bug|digest)-[a-z0-9-]+\b/gi;
var MATCH_CLASS_RE = /\b(record-id|relation|topic|keyword|semantic)\b/gi;
function uniqueMatches(text, pattern) {
  return [...new Set([...text.matchAll(pattern)].map((m) => m[0].toLowerCase()))].slice(0, 20);
}
function buildRecallDebugEntry(packets, timestamp = new Date().toISOString()) {
  const recallPacket = packets.find((packet) => packet.trim().startsWith("## SyberMem Recall Hints")) ?? "";
  if (!recallPacket)
    return { source: "opencode-chat-message", timestamp, event: "abstain", record_ids: [], has_digest: false, match_classes: [], reason: "no-high-signal-recall" };
  const recordIDs = uniqueMatches(recallPacket, RECORD_ID_RE);
  return { source: "opencode-chat-message", timestamp, event: "inject", record_ids: recordIDs, has_digest: recordIDs.some((recordID) => recordID.startsWith("digest-")), match_classes: uniqueMatches(recallPacket, MATCH_CLASS_RE), reason: "high-signal-recall" };
}
function appendRecallDebug(root, packets, timestamp) {
  boundedJsonlAppend(root, ".recall-debug.jsonl", buildRecallDebugEntry(packets, timestamp), 200);
}

// packages/opencode-plugin/src/record_intent.ts
import { writeFileSync as writeFileSync3 } from "fs";
import { join as join5 } from "path";
var BLOCKED_PATTERN = /(password\s*=|token\s*=|secret\s*=|bearer\s+[a-z0-9._-]+|api[_ -]?key\s*=|begin\s+(?:rsa\s+)?private\s+key|ignore\s+(?:all\s+)?previous|system\s+prompt|developer\s+message|<\/?(?:system|developer|tool)[^>]*>|\/sybermem-record\s+--|\u4E0D\u8981.{0,8}(\u8BB0\u5F55|\u6C89\u6DC0)|do\s+not\s+record|don'?t\s+record)/i;
var RULES = [
  { classification: "bug", id: "bug-fix", pattern: /(bug|fix|crash|regression|\u4FEE\u590D|\u7F3A\u9677|\u95EE\u9898)/i, reason: "explicit bug record request" },
  { classification: "decision", id: "decision", pattern: /(decision|architecture decision|adr|\u51B3\u5B9A|\u51B3\u7B56)/i, reason: "explicit decision record request" },
  { classification: "requirement", id: "requirement", pattern: /(requirement|\u9700\u6C42|must|\u5FC5\u987B|should)/i, reason: "explicit requirement record request" },
  { classification: "change", id: "change", pattern: /(record|\u8BB0\u5F55|\u6C89\u6DC0|\u5B9E\u73B0|\u5B8C\u6210|change)/i, reason: "explicit change record request" }
];
function classifyRecordIntent(text, createdAt = new Date().toISOString()) {
  if (!/(record|\u8BB0\u5F55|\u6C89\u6DC0)/i.test(text) || isBlockedPrompt(text))
    return null;
  for (const rule of RULES) {
    if (rule.pattern.test(text)) {
      return { record_intent: true, classification: rule.classification, action: "/sybermem-record", reason: rule.reason, source: "opencode-chat-message", created_at: createdAt, matched_pattern: rule.id, phrase: "" };
    }
  }
  return null;
}
function isBlockedPrompt(text) {
  return BLOCKED_PATTERN.test(text);
}
function isRecordIntentType(classification) {
  return classification === "change" || classification === "decision" || classification === "requirement" || classification === "bug";
}
function fromCoreCandidate(candidate, createdAt) {
  if (!isRecordIntentType(candidate.classification))
    return null;
  return {
    record_intent: true,
    classification: candidate.classification,
    action: "/sybermem-record",
    reason: typeof candidate.reason === "string" ? candidate.reason : "bounded core classifier match",
    source: "opencode-chat-message",
    created_at: createdAt,
    matched_pattern: "core-classifier",
    phrase: ""
  };
}
async function classifyWithCli($, root, text, createdAt) {
  try {
    const candidate = JSON.parse(await sybermemText($, root, ["record", "intent", "--prompt", text, "--format", "json"]));
    if (typeof candidate !== "object" || candidate === null)
      return null;
    const classification = Reflect.get(candidate, "classification");
    const reason = Reflect.get(candidate, "reason");
    if (typeof classification !== "string")
      return null;
    return fromCoreCandidate({ classification, reason: typeof reason === "string" ? reason : undefined }, createdAt);
  } catch {
    return null;
  }
}
async function captureRecordIntentWithCli($, root, text, createdAt = new Date().toISOString()) {
  if (isBlockedPrompt(text))
    return false;
  const metadata = await classifyWithCli($, root, text, createdAt) ?? classifyRecordIntent(text, createdAt);
  if (!metadata)
    return false;
  try {
    writeFileSync3(join5(root, ".sybermem", ".record-intent.json"), JSON.stringify(metadata, null, 2) + `
`, "utf-8");
    return true;
  } catch {
    return false;
  }
}

// packages/opencode-plugin/src/prompt_context.ts
var RECALL_STASH = new Map;
function extractPromptText(output) {
  return (output.parts ?? []).filter((p) => p.type === "text").map((p) => p.text ?? "").join(" ").trim();
}
function appendPromptPacket(packets, raw, heading) {
  const trimmed = raw.trim();
  if (trimmed.startsWith(heading))
    packets.push(trimmed);
}
async function collectPromptPackets($, root, text) {
  const packets = [];
  try {
    const raw = await sybermemText($, root, ["context", "recall", "--query", text, "--format", "markdown"]);
    appendPromptPacket(packets, raw, "## SyberMem Recall Hints");
  } catch {}
  try {
    const raw = await sybermemText($, root, ["context", "habit", "--context", text, "--delivery", "prompt-time", "--format", "markdown"]);
    appendPromptPacket(packets, raw, "## User Habit Reminder");
  } catch {}
  try {
    const section = scopedNormSection(parseNorms(await normsListText($, root, "scoped", text)));
    if (section.trim())
      packets.push(`## Relevant Project Norms
${section.trim().replace(/^### Relevant Project Norms\n?/, "")}`);
  } catch {}
  return packets;
}
function stashPromptPackets(sessionID, packets) {
  if (packets.length > 0)
    RECALL_STASH.set(sessionID, packets);
  else
    RECALL_STASH.delete(sessionID);
}
var NO_INJECTION = { injected: false, recallCount: 0, recallChars: 0, digestCount: 0, habitCount: 0, habitChars: 0, habitCandidate: false, normCount: 0, normChars: 0, injectedIds: [] };
function classifyPackets(packets) {
  if (packets.length === 0)
    return NO_INJECTION;
  let recallCount = 0;
  let recallChars = 0;
  let digestCount = 0;
  let habitCount = 0;
  let habitChars = 0;
  let habitCandidate = false;
  let normCount = 0;
  let normChars = 0;
  const injectedIds = new Set;
  for (const packet of packets) {
    const trimmed = packet.trim();
    if (trimmed.startsWith("## SyberMem Recall Hints")) {
      recallCount += countBullets(trimmed);
      recallChars += packet.length;
      collectIds(trimmed, injectedIds);
    } else if (trimmed.startsWith("## User Habit Reminder")) {
      const habitLines = trimmed.split(`
`).filter((line) => line.startsWith("- [habit-"));
      habitCount += habitLines.length;
      habitChars += packet.length;
      collectIds(trimmed, injectedIds);
      if (habitLines.length === 0)
        habitCandidate = true;
    } else if (trimmed.startsWith("## Relevant Project Norms")) {
      normCount += trimmed.split(`
`).filter((line) => line.startsWith("- [norm-")).length;
      normChars += packet.length;
      collectIds(trimmed, injectedIds);
    }
  }
  digestCount = [...injectedIds].filter((id) => id.startsWith("digest-")).length;
  return { injected: recallCount > 0 || habitCount > 0 || habitCandidate || normCount > 0, recallCount, recallChars, digestCount, habitCount, habitChars, habitCandidate, normCount, normChars, injectedIds: [...injectedIds] };
}
function collectIds(text, ids) {
  for (const match of text.matchAll(/\b(?:change|decision|requirement|bug|digest|habit|norm)-[a-z0-9-]+\b/gi))
    ids.add(match[0].toLowerCase());
}
function countBullets(packet) {
  return packet.split(`
`).filter((line) => /^-\s/.test(line.trim())).length;
}
function injectStashedPromptPackets(sessionID, output) {
  const packets = RECALL_STASH.get(sessionID);
  RECALL_STASH.delete(sessionID);
  if (!packets || packets.length === 0)
    return NO_INJECTION;
  const hints = packets.join(`

`);
  if (output.system)
    output.system.push(hints);
  else
    output.system = [hints];
  return classifyPackets(packets);
}

// packages/opencode-plugin/src/startup_context.ts
async function constitutionBlock2($, root) {
  try {
    return constitutionSection(parseNorms(await normsListText($, root, "global", "")));
  } catch {
    return "";
  }
}
async function latestDigestSection2($, root) {
  try {
    const parsed = JSON.parse(await digestLatestText($, root));
    if (typeof parsed !== "object" || parsed === null)
      return "";
    const conclusions = Reflect.get(parsed, "conclusions");
    if (!Array.isArray(conclusions) || conclusions.length === 0)
      return "";
    const title = typeof Reflect.get(parsed, "title") === "string" ? Reflect.get(parsed, "title") : "";
    const lines = conclusions.filter((c) => typeof c === "string").slice(0, 5);
    if (lines.length === 0)
      return "";
    return `
### Latest Digest${title ? `: ${title}` : ""}
${lines.join(`
`)}
`;
  } catch {
    return "";
  }
}
var PENDING_STARTUP = new Set;
function markPendingStartup(sessionID) {
  PENDING_STARTUP.add(sessionID);
}
function consumePendingStartup(sessionID) {
  return PENDING_STARTUP.delete(sessionID);
}
function appendStartupContext(output, startup) {
  const trimmed = startup.trim();
  if (!trimmed)
    return;
  if (output.system)
    output.system.push(trimmed);
  else
    output.system = [trimmed];
}
function numberField2(value, key) {
  if (typeof value !== "object" || value === null)
    return null;
  const field = Reflect.get(value, key);
  return typeof field === "number" ? field : null;
}
function stringField2(value, key) {
  if (typeof value !== "object" || value === null)
    return "";
  const field = Reflect.get(value, key);
  return typeof field === "string" ? field.trim() : "";
}
async function buildStartupContext($, root) {
  const parsed = parseIndex(root);
  const conclusions = parsed?.conclusions ?? [];
  const digestSection = await latestDigestSection2($, root);
  const constitution = await constitutionBlock2($, root);
  const habitAwareness = await habitAwarenessSection($, root);
  if (conclusions.length === 0 && !digestSection && !constitution && !habitAwareness)
    return null;
  const phaseInfo = parsePhaseIndex(root);
  const identity = parseProjectIdentity(root);
  const stale = await detectStaleSignal($, root);
  let context = `## SyberMem Startup Context

`;
  if (identity.exists && identity.slug)
    context += `Project: ${identity.slug} (${identity.projectId ?? "no id"}).

`;
  context += constitution;
  if (conclusions.length > 0) {
    context += `### Key Conclusions
`;
    for (const c of conclusions)
      context += `${c}
`;
  }
  if (phaseInfo.exists) {
    context += `
### Phase Index
Status: ${phaseInfo.status}. ${phaseInfo.confirmedCount} confirmed phases.
`;
    if (phaseInfo.activePhase)
      context += `Active phase: ${phaseInfo.activePhase}.
`;
  }
  context += digestSection;
  if (stale.stale)
    context += `
\u2B50 Heads-up: phase index trails HEAD by ${stale.commitsAhead} commits \u2014 conclusions may lag your latest work. Consider /sybermem-phase-analyze.
`;
  try {
    const staleDigestCount = numberField2(JSON.parse(await digestStatusText($, root)), "stale");
    if (staleDigestCount !== null && staleDigestCount > 0)
      context += `
\u2B50 Digest heads-up: ${staleDigestCount} digest(s) are stale \u2014 run /sybermem-digest to regenerate.
`;
  } catch {}
  try {
    const rec = JSON.parse(await sybermemText($, root, ["next-step", "--format", "json"]));
    const action = stringField2(rec, "action");
    const reason = stringField2(rec, "reason");
    if (action)
      context += `
### Recommended Next Step
${action}${reason ? ` \u2014 ${reason}` : ""}
`;
  } catch {}
  if (habitAwareness)
    context += habitAwareness;
  return context.length > 2500 ? `${context.substring(0, 2497)}...` : context;
}
async function habitAwarenessSection($, root) {
  try {
    const awareness = JSON.parse(await sybermemText($, root, ["habit", "awareness", "--format", "json"]));
    const activeHabits = numberField2(awareness, "active") ?? 0;
    const pendingIntent = typeof awareness === "object" && awareness !== null && Reflect.get(awareness, "pending_intent") === true;
    if (activeHabits === 0 && !pendingIntent)
      return "";
    let pendingNote = "";
    if (pendingIntent) {
      const reminder = typeof awareness === "object" && awareness !== null ? Reflect.get(awareness, "pending_reminder") : null;
      const message = typeof reminder === "object" && reminder !== null ? Reflect.get(reminder, "message") : null;
      pendingNote = typeof message === "string" && message.trim() ? ` ${message.trim()}` : " A reusable preference is pending \u2014 confirm with /sybermem-habit.";
    }
    return `
### User Habits
${activeHabits} active user habit${activeHabits === 1 ? "" : "s"} may apply; manage with /sybermem-habit.${pendingNote}
`;
  } catch {
    return "";
  }
}

// packages/opencode-plugin/src/recall_health_signal.ts
function parseRecallHealth(json) {
  const trimmed = json.trim();
  if (!trimmed)
    return null;
  try {
    const parsed = JSON.parse(trimmed);
    if (typeof parsed !== "object" || parsed === null)
      return null;
    const health = Reflect.get(parsed, "recall_health");
    if (typeof health !== "object" || health === null)
      return null;
    const status = Reflect.get(health, "status");
    const hint = Reflect.get(health, "hint");
    if (typeof status !== "string")
      return null;
    return { status, hint: typeof hint === "string" ? hint : "" };
  } catch {
    return null;
  }
}
function lowSignalRecallToast(health) {
  if (health.status === "low_signal") {
    const hint = health.hint ? ` \u2014 ${health.hint}` : "";
    return `\uD83D\uDCA1 SyberMem: recall quality is low${hint}`;
  }
  if (health.status === "low_relevance") {
    const hint = health.hint ? ` \u2014 ${health.hint}` : "";
    return `\uD83D\uDCA1 SyberMem: recall relevance is low${hint}`;
  }
  if (health.status === "low_measurability") {
    const hint = health.hint ? ` \u2014 ${health.hint}` : "";
    return `\uD83D\uDCA1 SyberMem: recall measurability is low${hint}`;
  }
  return null;
}

// packages/opencode-plugin/src/session_activity.ts
var RECORD_ID_RE2 = /\b(?:change|decision|requirement|bug|digest)-[a-z0-9-]+\b/gi;
var SKIP_PREFIXES2 = [".git/", ".sybermem/", "ADR/", ".claude/", ".opencode/", "node_modules/"];
var SESSIONS = new Map;
function freshActivity() {
  return {
    editedFiles: new Map,
    todoCompletedBatches: 0,
    lastToolSignal: null,
    injectedRecords: new Set,
    memoryTurns: 0,
    memoryItems: 0,
    memoryChars: 0,
    recallItems: 0,
    recallChars: 0,
    habitItems: 0,
    habitChars: 0,
    normItems: 0,
    normChars: 0,
    startupItems: 0,
    startupChars: 0
  };
}
function getSessionActivity(sessionID) {
  let activity = SESSIONS.get(sessionID);
  if (!activity) {
    activity = freshActivity();
    SESSIONS.set(sessionID, activity);
  }
  return activity;
}
function resetSessionActivity(sessionID) {
  SESSIONS.delete(sessionID);
}
function normalizePath(raw) {
  return raw.trim().replace(/\\/g, "/");
}
function isTracked(file) {
  return file.length > 0 && !SKIP_PREFIXES2.some((p) => file.startsWith(p));
}
function readString(source, keys) {
  if (typeof source !== "object" || source === null)
    return "";
  for (const key of keys) {
    const value = Reflect.get(source, key);
    if (typeof value === "string" && value)
      return value;
  }
  return "";
}
function extractEditedFile(properties) {
  const raw = readString(properties, ["file", "path", "filePath", "filename"]);
  return raw ? normalizePath(raw) : "";
}
function recordEditedFile(sessionID, file) {
  const normalized = normalizePath(file);
  if (!isTracked(normalized))
    return;
  const activity = getSessionActivity(sessionID);
  activity.editedFiles.set(normalized, (activity.editedFiles.get(normalized) ?? 0) + 1);
}
function isTodoBatchComplete(properties) {
  if (typeof properties !== "object" || properties === null)
    return false;
  const todos = Reflect.get(properties, "todos") ?? Reflect.get(properties, "items");
  if (!Array.isArray(todos) || todos.length === 0)
    return false;
  return todos.every((item) => {
    const status = readString(item, ["status", "state"]).toLowerCase();
    return status === "completed" || status === "done";
  });
}
function recordTodoUpdate(sessionID, properties) {
  if (isTodoBatchComplete(properties))
    getSessionActivity(sessionID).todoCompletedBatches += 1;
}
function classifyToolSignal(input, output) {
  const tool = readString(input, ["tool"]);
  if (tool !== "bash")
    return null;
  const args = Reflect.get(input, "args");
  const command = readString(args, ["command"]).toLowerCase();
  if (!command)
    return null;
  const exit = Reflect.get(output, "exit") ?? Reflect.get(output, "exitCode") ?? Reflect.get(output, "code");
  if (typeof exit === "number" && exit !== 0)
    return null;
  if (/\b(pytest|vitest|jest|bun test|go test|cargo test|npm test|yarn test|pnpm test)\b/.test(command))
    return "tests_passed";
  if (/\b(build|tsc|cargo build|go build|make)\b/.test(command))
    return "build_ok";
  return null;
}
function recordToolExecution(sessionID, input, output) {
  const signal = classifyToolSignal(input, output);
  if (signal)
    getSessionActivity(sessionID).lastToolSignal = signal;
}
function recordInjectedRecords(sessionID, packets) {
  const recallPacket = packets.find((packet) => packet.trim().startsWith("## SyberMem Recall Hints"));
  if (!recallPacket)
    return;
  const activity = getSessionActivity(sessionID);
  for (const match of recallPacket.matchAll(RECORD_ID_RE2))
    activity.injectedRecords.add(match[0].toLowerCase());
}
function recordMemoryUsage(sessionID, entry) {
  if (entry.total_items === 0)
    return;
  const activity = getSessionActivity(sessionID);
  activity.memoryTurns += 1;
  activity.memoryItems += entry.total_items;
  activity.memoryChars += entry.total_chars;
  activity.recallItems += entry.recall_items;
  activity.recallChars += entry.recall_chars;
  activity.habitItems += entry.habit_items;
  activity.habitChars += entry.habit_chars;
  activity.normItems += entry.norm_items;
  activity.normChars += entry.norm_chars;
  activity.startupItems += entry.startup_items;
  activity.startupChars += entry.startup_chars;
}

// packages/opencode-plugin/src/recall_outcome.ts
var EMPTY_OUTCOME = { recallEvidenceAvailable: true, injected: 0, measurable: 0, unmeasurable: 0, hit: 0, precision: null, hitRecords: [], missRecords: [] };
var UNAVAILABLE_OUTCOME = { recallEvidenceAvailable: false, injected: 0, measurable: 0, unmeasurable: 0, hit: 0, precision: null, hitRecords: [], missRecords: [] };
function normalize(path) {
  return path.trim().replace(/\\/g, "/");
}
function computeRecallOutcome(injected, relatedFilesByRecord, editedFiles) {
  const edited = new Set([...editedFiles].map(normalize));
  const hitRecords = [];
  const missRecords = [];
  let unmeasurable = 0;
  for (const rawId of injected) {
    const id = rawId.toLowerCase();
    const related = (relatedFilesByRecord[id] ?? relatedFilesByRecord[rawId] ?? []).map(normalize);
    if (related.length === 0) {
      unmeasurable += 1;
      continue;
    }
    if (related.some((file) => edited.has(file)))
      hitRecords.push(id);
    else
      missRecords.push(id);
  }
  const injectedCount = hitRecords.length + missRecords.length;
  if (injectedCount === 0)
    return { ...EMPTY_OUTCOME, unmeasurable };
  return {
    recallEvidenceAvailable: true,
    injected: injectedCount,
    measurable: injectedCount,
    unmeasurable,
    hit: hitRecords.length,
    precision: hitRecords.length / injectedCount,
    hitRecords,
    missRecords
  };
}
function parseRecordFilesJson(raw) {
  try {
    const parsed = JSON.parse(raw.trim());
    if (typeof parsed !== "object" || parsed === null)
      return {};
    const records = Reflect.get(parsed, "records");
    if (typeof records !== "object" || records === null)
      return {};
    const mapping = {};
    for (const [key, value] of Object.entries(records)) {
      if (Array.isArray(value))
        mapping[key.toLowerCase()] = value.filter((item) => typeof item === "string");
    }
    return mapping;
  } catch {
    return {};
  }
}
async function flushRecallOutcome($, root, activity, sessionID, timestamp = new Date().toISOString()) {
  const injected = [...activity.injectedRecords];
  if (activity.memoryTurns === 0)
    return EMPTY_OUTCOME;
  let mapping = {};
  let recallEvidenceAvailable = true;
  if (injected.length > 0) {
    try {
      mapping = parseRecordFilesJson(await recordFilesText($, root, injected.join(",")));
    } catch {
      recallEvidenceAvailable = false;
    }
  }
  const outcome = recallEvidenceAvailable ? computeRecallOutcome(injected, mapping, new Set(activity.editedFiles.keys())) : UNAVAILABLE_OUTCOME;
  boundedJsonlAppend(root, ".memory-usage.jsonl", {
    schema_version: 1,
    host: "opencode",
    event: "session_outcome",
    timestamp,
    session_id: sessionID,
    memory_turns: activity.memoryTurns,
    memory_items: activity.memoryItems,
    memory_chars: activity.memoryChars,
    recall_items: activity.recallItems,
    recall_chars: activity.recallChars,
    habit_items: activity.habitItems,
    habit_chars: activity.habitChars,
    norm_items: activity.normItems,
    norm_chars: activity.normChars,
    startup_items: activity.startupItems,
    startup_chars: activity.startupChars,
    edited_files: activity.editedFiles.size,
    todo_completed_batches: activity.todoCompletedBatches,
    tool_signal: activity.lastToolSignal,
    recall_evidence_available: outcome.recallEvidenceAvailable,
    recall_measurable: outcome.measurable,
    recall_unmeasurable: outcome.unmeasurable,
    recall_hit: outcome.hit,
    recall_precision: outcome.precision
  }, 200);
  if (!outcome.recallEvidenceAvailable || outcome.injected === 0)
    return outcome;
  boundedJsonlAppend(root, ".recall-outcomes.jsonl", {
    timestamp,
    session: sessionID,
    injected: outcome.injected,
    measurable: outcome.measurable,
    unmeasurable: outcome.unmeasurable,
    hit: outcome.hit,
    precision: outcome.precision,
    hit_records: outcome.hitRecords,
    miss_records: outcome.missRecords
  }, 200);
  return outcome;
}

// packages/opencode-plugin/src/habit_intent.ts
var NO_CAPTURE = { captured: false, habitType: "", suggestedScope: "" };
var DURABLE_PREFERENCE_RE = /(\b(always\s+(?:prefer|use|reply|respond|run|keep|write|ask|show|include|avoid)|usually\s+(?:i\s+)?(?:prefer|use|want|ask|run|keep|write)|(?:please\s+)?remember\s+(?:that\s+)?(?:i\s+)?(?:prefer|want|usually|always)|i\s+prefer\b|i\s+usually\b|by\s+default\b|make\s+this\s+the\s+default\b|from\s+now\s+on\b)|\u4EE5\u540E(?:\u90FD|\u8BF7|\u8BB0\u5F97|\u9ED8\u8BA4|\u4E00\u5F8B)?|\u8BF7\u8BB0\u4F4F|\u5E2E\u6211\u8BB0\u4F4F|\u8BB0\u4F4F\u6211|\u6211(?:\u4E60\u60EF|\u504F\u597D|\u5E0C\u671B)|\u6BCF\u6B21\u90FD|\u9ED8\u8BA4(?:\u7528|\u5148|\u90FD)?|\u4E00\u5F8B(?:\u7528|\u5148|\u90FD)?|\u603B\u662F(?:\u7528|\u5148|\u90FD)?)/i;
var NOISY_HABIT_DISCUSSION_RE = /(why|debug|investigate|research|review|analy[sz]e|improve|design|logic|classifier|candidate|capture|\u4E3A\u4EC0\u4E48|\u600E\u4E48|\u8C03\u7814|\u7814\u7A76|\u8BC4\u5BA1|\u5BA1\u67E5|\u6539\u8FDB|\u8BBE\u8BA1|\u903B\u8F91|\u5019\u9009|\u6355\u83B7|\u547D\u4E2D).{0,80}(habit|preference|memory|norm|\u4E60\u60EF|\u504F\u597D|\u8BB0\u5FC6|\u89C4\u8303|\u7EA6\u5B9A)|(habit|preference|memory|norm|\u4E60\u60EF|\u504F\u597D|\u8BB0\u5FC6|\u89C4\u8303|\u7EA6\u5B9A).{0,80}(why|debug|investigate|research|review|analy[sz]e|improve|design|logic|classifier|candidate|capture|\u4E3A\u4EC0\u4E48|\u600E\u4E48|\u8C03\u7814|\u7814\u7A76|\u8BC4\u5BA1|\u5BA1\u67E5|\u6539\u8FDB|\u8BBE\u8BA1|\u903B\u8F91|\u5019\u9009|\u6355\u83B7|\u547D\u4E2D)/i;
var AGENT_PROMPT_PREFIX_RE = /^\s*(?:TASK|CONTEXT|AXIS|EXPECTED OUTCOME|MUST DO|MUST NOT DO|REQUEST):/i;
var ONE_OFF_WORK_RE = /(fix|repair|update|submit|publish|release|commit|create\s+pr|\u4FEE\u590D|\u66F4\u65B0|\u63D0\u4EA4|\u53D1\u5E03|\u4E0A\u7EBF).{0,80}(pr|readme|docs?|todo|ui|bug|\u6587\u6863|\u5F85\u529E|\u89C4\u8303|\u7EA6\u5B9A|\u9879\u76EE|\u4E0B\u62C9|\u6309\u94AE)/i;
function looksLikeHabitIntent(text) {
  return DURABLE_PREFERENCE_RE.test(text) && !isNoisyHabitCandidate(text);
}
function isNoisyHabitCandidate(text) {
  return AGENT_PROMPT_PREFIX_RE.test(text) || NOISY_HABIT_DISCUSSION_RE.test(text) || ONE_OFF_WORK_RE.test(text);
}
async function captureHabitIntentWithCli($, root, text) {
  if (!text || !looksLikeHabitIntent(text))
    return NO_CAPTURE;
  try {
    const parsed = JSON.parse(await sybermemText($, root, ["habit", "intent", "--prompt", text, "--format", "json"]));
    if (typeof parsed !== "object" || parsed === null)
      return NO_CAPTURE;
    if (Reflect.get(parsed, "captured") !== true)
      return NO_CAPTURE;
    const candidate = Reflect.get(parsed, "candidate");
    const habitType = typeof candidate === "object" && candidate !== null ? Reflect.get(candidate, "habit_type") : "";
    const suggestedScope = typeof candidate === "object" && candidate !== null ? Reflect.get(candidate, "suggested_scope") : "";
    return {
      captured: true,
      habitType: typeof habitType === "string" ? habitType : "",
      suggestedScope: typeof suggestedScope === "string" ? suggestedScope : ""
    };
  } catch {
    return NO_CAPTURE;
  }
}

// packages/opencode-plugin/src/version_signal.ts
import { existsSync as existsSync5, readFileSync as readFileSync4 } from "fs";
import { join as join6 } from "path";
function userHome2() {
  return process.env.USERPROFILE ?? process.env.HOME ?? null;
}
function readInstalledVersion() {
  const home = userHome2();
  if (!home)
    return "";
  const marker = join6(home, ".claude", "sybermem", "VERSION");
  if (!existsSync5(marker))
    return "";
  try {
    return readFileSync4(marker, "utf-8").trim();
  } catch {
    return "";
  }
}
function isManagedProject(root) {
  return existsSync5(join6(root, ".sybermem", "project.yaml"));
}
function readProjectVersion(root) {
  const proj = join6(root, ".sybermem", "project.yaml");
  if (!existsSync5(proj))
    return "";
  try {
    for (const raw of readFileSync4(proj, "utf-8").split(`
`)) {
      const line = raw.trim();
      if (line.startsWith("sybermem_version:"))
        return line.split(":").slice(1).join(":").trim();
    }
  } catch {}
  return "";
}
function parse(version) {
  return version.trim().split(".").map((raw) => {
    let digits = "";
    for (const ch of raw) {
      if (ch >= "0" && ch <= "9")
        digits += ch;
      else
        break;
    }
    return digits ? Number.parseInt(digits, 10) : 0;
  });
}
function compareVersions(a, b) {
  const pa = parse(a);
  const pb = parse(b);
  const width = Math.max(pa.length, pb.length);
  for (let i = 0;i < width; i++) {
    const x = pa[i] ?? 0;
    const y = pb[i] ?? 0;
    if (x < y)
      return -1;
    if (x > y)
      return 1;
  }
  return 0;
}
function projectNeedsUpdate(root, installed) {
  if (!installed || !isManagedProject(root))
    return false;
  const project = readProjectVersion(root);
  if (!project)
    return true;
  return compareVersions(project, installed) < 0;
}
function updateNudgeMessage(root) {
  const installed = readInstalledVersion();
  if (!projectNeedsUpdate(root, installed))
    return null;
  const project = readProjectVersion(root);
  const wasRefreshed = project ? `this project was last refreshed with ${project}` : `this project predates SyberMem version tracking`;
  return `\u2B50 SyberMem ${installed} is installed; ${wasRefreshed}. Run /sybermem-update to apply the latest fixes.`;
}

// packages/opencode-plugin/src/remote_version.ts
import { existsSync as existsSync6, mkdirSync, readFileSync as readFileSync5, writeFileSync as writeFileSync4 } from "fs";
import { dirname, join as join7 } from "path";
var REMOTE_VERSION_URL = "https://raw.githubusercontent.com/goudaren0528/sybermem/main/VERSION";
var CACHE_TTL_MS = 24 * 60 * 60 * 1000;
var FETCH_TIMEOUT_MS = 3000;
function userHome3() {
  return process.env.USERPROFILE ?? process.env.HOME ?? null;
}
function remoteVersionCachePath() {
  const home = userHome3();
  if (!home)
    return null;
  return join7(home, ".claude", "sybermem", ".remote-version-cache.json");
}
function remoteCheckDisabled() {
  const flag = process.env.SYBERMEM_NO_REMOTE_CHECK;
  return flag === "1" || flag === "true";
}
function parseRemoteVersionCache(raw) {
  try {
    const data = JSON.parse(raw);
    if (typeof data !== "object" || data === null)
      return null;
    const remote = Reflect.get(data, "remote_version");
    const checked = Reflect.get(data, "checked_at");
    if (typeof remote !== "string" || !remote.trim())
      return null;
    if (typeof checked !== "string" || !checked.trim())
      return null;
    return { remote_version: remote.trim(), checked_at: checked.trim() };
  } catch {
    return null;
  }
}
function readRemoteVersionCache() {
  const path = remoteVersionCachePath();
  if (!path || !existsSync6(path))
    return null;
  try {
    return parseRemoteVersionCache(readFileSync5(path, "utf-8"));
  } catch {
    return null;
  }
}
function writeRemoteVersionCache(cache) {
  const path = remoteVersionCachePath();
  if (!path)
    return;
  try {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync4(path, JSON.stringify(cache, null, 2) + `
`, "utf-8");
  } catch {}
}
function cacheIsStale(cache, now = Date.now()) {
  if (!cache)
    return true;
  const checkedAt = Date.parse(cache.checked_at);
  if (Number.isNaN(checkedAt))
    return true;
  return now - checkedAt >= CACHE_TTL_MS;
}
function remoteIsNewer(remoteVersion, installedVersion) {
  if (!remoteVersion || !installedVersion)
    return false;
  return compareVersions(remoteVersion, installedVersion) > 0;
}
function remoteUpdateNudgeMessage(cache, installed) {
  if (remoteCheckDisabled())
    return null;
  if (!cache || !installed)
    return null;
  if (!remoteIsNewer(cache.remote_version, installed))
    return null;
  return `\u2B50 SyberMem ${cache.remote_version} is available on GitHub (you have ${installed}). Re-run the install script to upgrade this machine.`;
}
async function fetchRemoteVersion() {
  try {
    const controller = new AbortController;
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const response = await fetch(REMOTE_VERSION_URL, {
        signal: controller.signal,
        headers: { Accept: "text/plain" }
      });
      if (!response.ok)
        return null;
      const body = (await response.text()).trim();
      const firstLine = body.split(`
`)[0]?.trim() ?? "";
      if (!firstLine || firstLine.length > 32 || !/^[0-9]/.test(firstLine))
        return null;
      return firstLine;
    } finally {
      clearTimeout(timer);
    }
  } catch {
    return null;
  }
}
async function refreshRemoteVersionCache(now = Date.now()) {
  if (remoteCheckDisabled())
    return;
  const remote = await fetchRemoteVersion();
  if (!remote)
    return;
  writeRemoteVersionCache({ remote_version: remote, checked_at: new Date(now).toISOString() });
}
function evaluateRemoteVersion() {
  if (remoteCheckDisabled())
    return null;
  const cache = readRemoteVersionCache();
  const installed = readInstalledVersion();
  if (cacheIsStale(cache)) {
    refreshRemoteVersionCache().catch(() => {});
  }
  return remoteUpdateNudgeMessage(cache, installed);
}

// packages/opencode-plugin/src/reply_marker.ts
var PENDING = new Map;
var MARKED = new Set;
function replyMarkerEnabled() {
  const raw = (process.env.SYBERMEM_REPLY_MARKER ?? "").trim().toLowerCase();
  return raw === "1" || raw === "true" || raw === "yes" || raw === "on";
}
function armReplyMarker(sessionID, recallCount, habitCount) {
  if (!sessionID)
    return;
  if (recallCount <= 0 && habitCount <= 0) {
    PENDING.delete(sessionID);
    return;
  }
  PENDING.set(sessionID, { recallCount, habitCount });
}
function formatMarker(m) {
  const parts = [];
  if (m.recallCount > 0)
    parts.push(`\u2B50 ${m.recallCount} \u6761\u8BB0\u5FC6`);
  if (m.habitCount > 0)
    parts.push(`\uD83E\uDDE0 ${m.habitCount} \u6761\u4E60\u60EF`);
  return `> SyberMem: \u672C\u8F6E\u53C2\u8003\u4E86 ${parts.join(" \xB7 ")}`;
}
function applyReplyMarker(sessionID, messageID, text) {
  if (!replyMarkerEnabled())
    return text;
  if (!sessionID || !messageID)
    return text;
  if (MARKED.has(messageID))
    return text;
  const pending = PENDING.get(sessionID);
  if (!pending)
    return text;
  MARKED.add(messageID);
  PENDING.delete(sessionID);
  if (MARKED.size > 500)
    MARKED.clear();
  return `${formatMarker(pending)}

${text}`;
}

// packages/opencode-plugin/src/memory_usage.ts
var RECORD_ID_RE3 = /\b(?:change|decision|requirement|bug|digest|habit|norm)-[a-z0-9-]+\b/gi;
var STRUCTURED_ID_RE = /^\s*-\s*\[([^\]]{1,120})\]/;
var MAX_PACKET_SCAN_CHARS = 8000;
var MAX_TOTAL_SCAN_CHARS = 24000;
var MAX_SESSION_ID_CHARS = 80;
var MAX_INJECTED_IDS = 40;
function boundText(value, maxChars) {
  return value.length > maxChars ? value.slice(0, maxChars) : value;
}
function structuredIds(text) {
  const ids = [];
  for (const line of boundText(text, MAX_PACKET_SCAN_CHARS).split(`
`)) {
    const id = line.match(STRUCTURED_ID_RE)?.[1]?.match(RECORD_ID_RE3)?.[0];
    if (id)
      ids.push(id.toLowerCase());
  }
  return ids;
}
function uniqueStructuredIds(packets, startup) {
  const ids = new Set;
  let scanned = 0;
  for (const text of [...packets, startup]) {
    if (scanned >= MAX_TOTAL_SCAN_CHARS || ids.size >= MAX_INJECTED_IDS)
      break;
    const remaining = MAX_TOTAL_SCAN_CHARS - scanned;
    const bounded = boundText(text, Math.min(MAX_PACKET_SCAN_CHARS, remaining));
    scanned += bounded.length;
    for (const id of structuredIds(bounded)) {
      ids.add(id);
      if (ids.size >= MAX_INJECTED_IDS)
        break;
    }
  }
  return [...ids];
}
function packetChars(packets, heading) {
  return packets.find((packet) => packet.trim().startsWith(heading))?.length ?? 0;
}
function startupItemCount(startup) {
  if (!startup)
    return 0;
  const bullets = startup.split(`
`).filter((line) => /^-\s/.test(line.trim())).length;
  return bullets > 0 ? bullets : 1;
}
function buildMemoryUsageEntry(input, options = {}) {
  const summary = classifyPackets(input.packets);
  const startup = input.startup.trim();
  const startupItems = startupItemCount(startup);
  const recallChars = packetChars(input.packets, "## SyberMem Recall Hints");
  const habitChars = packetChars(input.packets, "## User Habit Reminder");
  const normChars = packetChars(input.packets, "## Relevant Project Norms");
  const injectedIds = uniqueStructuredIds(input.packets, startup);
  const digestItems = injectedIds.filter((id) => id.startsWith("digest-")).length;
  return {
    schema_version: 1,
    timestamp: options.timestamp ?? new Date().toISOString(),
    host: "opencode",
    session_id: boundText(input.sessionID, MAX_SESSION_ID_CHARS),
    total_items: summary.recallCount + summary.habitCount + summary.normCount + startupItems,
    total_chars: recallChars + habitChars + normChars + startup.length,
    digest_items: digestItems,
    recall_items: summary.recallCount,
    recall_chars: recallChars,
    habit_items: summary.habitCount,
    habit_chars: habitChars,
    norm_items: summary.normCount,
    norm_chars: normChars,
    startup_items: startupItems,
    startup_chars: startup.length,
    injected_ids: injectedIds,
    startup_present: startupItems > 0
  };
}
function appendMemoryUsage(root, input, options = {}) {
  const entry = buildMemoryUsageEntry(input, options);
  if (entry.total_items > 0)
    boundedJsonlAppend(root, ".memory-usage.jsonl", entry, 200);
  return entry;
}

// packages/opencode-plugin/src/injection_toast.ts
async function showToast(client, message) {
  try {
    await client.tui.showToast({ body: { message, variant: "info" } });
  } catch {}
}
var TOAST_MIN_GAP_MS = 2500;
var TOAST_QUEUE = [];
var draining = false;
function sleep(ms) {
  return new Promise((resolve2) => setTimeout(resolve2, ms));
}
async function drainToastQueue() {
  if (draining)
    return;
  draining = true;
  try {
    while (TOAST_QUEUE.length > 0) {
      const next = TOAST_QUEUE.shift();
      if (!next)
        break;
      await showToast(next.client, next.message);
      if (TOAST_QUEUE.length > 0)
        await sleep(TOAST_MIN_GAP_MS);
    }
  } finally {
    draining = false;
  }
}
function enqueueToast(client, message) {
  TOAST_QUEUE.push({ client, message });
  drainToastQueue().catch(() => {});
}
var LAST_TOAST = new Map;
var TOAST_COOLDOWN_MS = 30000;
function throttledToast(client, key, message) {
  const now = Date.now();
  const last = LAST_TOAST.get(key) ?? 0;
  if (now - last < TOAST_COOLDOWN_MS)
    return;
  LAST_TOAST.set(key, now);
  enqueueToast(client, message);
}
function buildPromptInjectionToastSummary(summary, usageEntry) {
  const laneCounts = [];
  if (summary.recallCount > 0)
    laneCounts.push({ lane: "recall", count: summary.recallCount });
  if (summary.habitCount > 0)
    laneCounts.push({ lane: "habit", count: summary.habitCount });
  if (summary.normCount > 0)
    laneCounts.push({ lane: "norm", count: summary.normCount });
  if (laneCounts.length === 0)
    return null;
  return {
    totalItems: usageEntry.recall_items + usageEntry.habit_items + usageEntry.norm_items,
    totalChars: usageEntry.recall_chars + usageEntry.habit_chars + usageEntry.norm_chars,
    laneCounts
  };
}
function promptInjectionToastMessage(summary) {
  const laneCounts = summary.laneCounts.map(({ lane, count }) => `${lane}=${count}`).join(", ");
  return `\u2B50 SyberMem \u6CE8\u5165\u6458\u8981: items=${summary.totalItems}, chars=${summary.totalChars}, ${laneCounts}`;
}
function pendingHabitToast() {
  return "\uD83D\uDCA1 SyberMem \u6709\u4E00\u6761\u5F85\u786E\u8BA4\u7684\u4E60\u60EF\u5019\u9009 \u2014 \u7528 /sybermem-habit \u786E\u8BA4\u540E\u5373\u53EF\u5728\u540E\u7EED\u4F1A\u8BDD\u88AB\u6CE8\u5165";
}
function habitCandidateToast(habitIntent) {
  if (habitIntent.captured && habitIntent.suggestedScope === "project") {
    return "\uD83D\uDCA1 SyberMem \u53D1\u73B0\u4E00\u6761\u50CF\u662F\u672C\u9879\u76EE\u7684\u7EA6\u5B9A \u2014 \u53EF\u7528 /sybermem-record \u8BB0\u4E3A\u51B3\u7B56/\u9700\u6C42\uFF0C\u6216 /sybermem-habit \u786E\u8BA4";
  }
  if (habitIntent.captured && habitIntent.suggestedScope === "user") {
    return "\uD83D\uDCA1 SyberMem \u53D1\u73B0\u4E00\u6761\u53EF\u590D\u7528\u7684\u4E2A\u4EBA\u4E60\u60EF \u2014 \u9700\u8981\u7684\u8BDD\u7528 /sybermem-habit \u4E00\u6B65\u786E\u8BA4";
  }
  return "\uD83D\uDCA1 SyberMem \u53D1\u73B0\u4E00\u6761\u53EF\u590D\u7528\u7684\u504F\u597D/\u89C4\u8303 \u2014 \u9700\u8981\u7684\u8BDD\u7528 /sybermem-habit \u4E00\u6B65\u786E\u8BA4\uFF08\u4F1A\u95EE\u4F60\u8BB0\u6210\u4E60\u60EF\u8FD8\u662F\u9879\u76EE\u7EA6\u5B9A\uFF09";
}

// packages/opencode-plugin/src/pending_habit.ts
var SURFACED_CANDIDATE = new Map;
function resetPendingHabit(sessionID) {
  SURFACED_CANDIDATE.delete(sessionID);
}
async function readPendingHabitReminder($, root) {
  try {
    const parsed = JSON.parse(await sybermemText($, root, ["habit", "awareness", "--format", "json"]));
    if (typeof parsed !== "object" || parsed === null)
      return null;
    const reminder = Reflect.get(parsed, "pending_reminder");
    if (typeof reminder !== "object" || reminder === null)
      return null;
    const message = Reflect.get(reminder, "message");
    const createdAt = Reflect.get(reminder, "created_at");
    const fingerprint = Reflect.get(reminder, "fingerprint");
    if (typeof message !== "string" || !message.trim())
      return null;
    return {
      message: message.trim(),
      createdAt: typeof createdAt === "string" ? createdAt : "",
      fingerprint: typeof fingerprint === "string" ? fingerprint : ""
    };
  } catch {
    return null;
  }
}
async function injectPendingHabitReminder($, root, sessionID, output) {
  const reminder = await readPendingHabitReminder($, root);
  if (!reminder)
    return null;
  const key = reminder.fingerprint || reminder.createdAt || reminder.message;
  if (SURFACED_CANDIDATE.get(sessionID) === key)
    return null;
  SURFACED_CANDIDATE.set(sessionID, key);
  const block = `## SyberMem Habit Candidate

${reminder.message}`;
  if (output.system)
    output.system.push(block);
  else
    output.system = [block];
  return reminder;
}

// packages/opencode-plugin/src/plugin.ts
function readSessionID(source) {
  if (typeof source !== "object" || source === null)
    return "";
  for (const key of ["sessionID", "sessionId", "session"]) {
    const value = Reflect.get(source, key);
    if (typeof value === "string" && value)
      return value;
  }
  return "";
}
async function handleSessionCreated(args, root, sessionID) {
  const versionNudge = updateNudgeMessage(root);
  if (versionNudge)
    throttledToast(args.client, "version-outdated", versionNudge);
  const remoteNudge = evaluateRemoteVersion();
  if (remoteNudge)
    throttledToast(args.client, "remote-outdated", remoteNudge);
  const parsed = parseIndex(root);
  if (!parsed || parsed.conclusions.length === 0)
    return;
  if (sessionID)
    markPendingStartup(sessionID);
  const stale = await detectStaleSignal(args.$, root);
  const staleNote = stale.stale ? ` (phase-index ${stale.commitsAhead} commits behind)` : "";
  const commitsSinceRecord = await countCommitsSinceLastRecord(args.$, root);
  const recordNote = commitsSinceRecord >= 3 ? `. ${commitsSinceRecord} commits since last record \u2014 consider /sybermem-record` : "";
  const ahaMarker = stale.stale || commitsSinceRecord >= 3 ? "\u2B50 " : "";
  enqueueToast(args.client, `${ahaMarker}SyberMem: loaded ${parsed.conclusions.length} key conclusions${staleNote}${recordNote}`);
}
async function maybeToastRecallHealth(args, root) {
  try {
    const health = parseRecallHealth(await memoryStatsText(args.$, root));
    if (!health)
      return;
    const message = lowSignalRecallToast(health);
    if (message)
      throttledToast(args.client, "recall-health", message);
  } catch {}
}
async function maybeToastDigestBacklog(args, root) {
  try {
    const backlog = parseDigestBacklog(await digestStatusText(args.$, root));
    if (!backlog)
      return;
    const message = digestBacklogToast(backlog);
    if (message)
      throttledToast(args.client, "digest-backlog", message);
  } catch {}
}
async function flushSessionRelevance(args, root, sessionID) {
  if (!sessionID)
    return;
  try {
    const activity = getSessionActivity(sessionID);
    await flushRecallOutcome(args.$, root, activity, sessionID);
    compactJsonlJournal(root, ".memory-usage.jsonl", 200);
    compactJsonlJournal(root, ".recall-outcomes.jsonl", 200);
    compactJsonlJournal(root, ".recall-debug.jsonl", 200);
  } catch {} finally {
    resetSessionActivity(sessionID);
    resetPendingHabit(sessionID);
  }
}
function deriveActivitySignal(sessionID) {
  const activity = getSessionActivity(sessionID);
  let editFocus = null;
  let topCount = 1;
  for (const [file, count] of activity.editedFiles) {
    if (count > topCount) {
      topCount = count;
      editFocus = file;
    }
  }
  return { toolSignal: activity.lastToolSignal, todoCompletedBatches: activity.todoCompletedBatches, editFocus };
}
async function handleSessionIdle(args, root, sessionID) {
  const trail = trailFiles(await getChangedFiles(args.$, root));
  if (trail.length === 0)
    return;
  const fingerprint = JSON.stringify(trail);
  const state = loadNudgeState(root);
  if (state.lastFingerprint === fingerprint)
    return;
  if (overlapsRecentAutoTrails(root, trail)) {
    saveNudgeState(root, { ...state, lastFingerprint: fingerprint });
    return;
  }
  const commitsSince = await countCommitsSinceLastRecord(args.$, root);
  const activity = sessionID ? deriveActivitySignal(sessionID) : undefined;
  const followup = classifyFollowup(trail, commitsSince, state, activity);
  const today = new Date().toISOString().split("T")[0];
  appendAutoTrailJournal(root, today, trail, detectHighLevelAreas(trail), followup.type);
  const windows = { ...state.theme_recent_stops ?? {} };
  windows[followup.themeKey] = [...windows[followup.themeKey] ?? [], today].slice(-THEME_WINDOW_SIZE);
  const digestGuard = { ...state.digest_nudged_at_window_len ?? {} };
  if (followup.type === "digest")
    digestGuard[followup.themeKey] = windows[followup.themeKey].length;
  saveNudgeState(root, { ...state, lastFingerprint: fingerprint, lastNudgeCommitCount: commitsSince, theme_recent_stops: windows, digest_nudged_at_window_len: digestGuard, last_theme: followup.themeKey, last_nudge_type: followup.type, last_nudge: followup.type === "none" ? state.last_nudge : { platform: "opencode", type: followup.type, theme: followup.themeKey, date: today } });
  if (followup.type !== "none")
    enqueueToast(args.client, followup.message ?? "SyberMem: consider recording this work.");
}
var SyberMemPlugin = async ({ $, directory, client }) => {
  const args = { $, directory, client };
  const root = resolveRoot(directory);
  return {
    event: async ({ event }) => {
      if (!root)
        return;
      const sessionID = event.properties?.info?.id ?? "";
      if (event.type === "session.created")
        await handleSessionCreated(args, root, sessionID);
      if (event.type === "file.edited") {
        try {
          const file = extractEditedFile(event.properties);
          if (file && sessionID)
            recordEditedFile(sessionID, file);
        } catch {}
      }
      if (event.type === "todo.updated" && sessionID) {
        try {
          recordTodoUpdate(sessionID, event.properties);
        } catch {}
      }
      if (event.type === "session.idle") {
        try {
          await handleSessionIdle(args, root, sessionID);
        } catch {}
        await flushSessionRelevance(args, root, sessionID);
        await maybeToastRecallHealth(args, root);
        await maybeToastDigestBacklog(args, root);
      }
    },
    "tool.execute.after": async (input, output) => {
      if (!root)
        return;
      try {
        const sessionID = readSessionID(input);
        if (sessionID)
          recordToolExecution(sessionID, input, output);
      } catch {}
    },
    "chat.message": async ({ sessionID }, output) => {
      if (!root)
        return;
      const text = extractPromptText(output);
      if (!text)
        return;
      await captureRecordIntentWithCli(args.$, root, text);
      const habitIntent = await captureHabitIntentWithCli(args.$, root, text);
      const packets = await collectPromptPackets(args.$, root, text);
      appendRecallDebug(root, packets);
      if (sessionID)
        recordInjectedRecords(sessionID, packets);
      stashPromptPackets(sessionID, packets);
      const summary = classifyPackets(packets);
      if (habitIntent.captured || summary.habitCandidate) {
        throttledToast(args.client, "habit-candidate", habitCandidateToast(habitIntent));
      }
    },
    "experimental.chat.system.transform": async ({ sessionID }, output) => {
      if (!root)
        return;
      const packets = RECALL_STASH.get(sessionID ?? "") ?? [];
      let startup = "";
      if (consumePendingStartup(sessionID ?? "")) {
        startup = await buildStartupContext(args.$, root) ?? "";
        if (startup) {
          appendStartupContext(output, startup);
          throttledToast(args.client, "startup-context", "\u2B50 SyberMem: injected project startup context into this session");
        }
      }
      const summary = injectStashedPromptPackets(sessionID ?? "", output);
      try {
        const pending = await injectPendingHabitReminder(args.$, root, sessionID ?? "", output);
        if (pending)
          throttledToast(args.client, "habit-pending", pendingHabitToast());
      } catch {}
      const usageEntry = appendMemoryUsage(root, { sessionID: sessionID ?? "", packets, startup });
      if (sessionID)
        recordMemoryUsage(sessionID, usageEntry);
      const promptInjectionToast = buildPromptInjectionToastSummary(summary, usageEntry);
      if (promptInjectionToast) {
        throttledToast(args.client, "prompt-memory-injected", promptInjectionToastMessage(promptInjectionToast));
      }
      armReplyMarker(sessionID ?? "", summary.recallCount, summary.habitCount);
    },
    "experimental.text.complete": async (input, output) => {
      if (!root)
        return;
      try {
        output.text = applyReplyMarker(input.sessionID, input.messageID, output.text);
      } catch {}
    },
    "experimental.session.compacting": async (_input, output) => {
      if (!root)
        return;
      const context = await buildCompactionContext(args.$, root);
      if (context)
        output.context.push(context);
    }
  };
};
export {
  SyberMemPlugin
};
