/**
 * SyberMem OpenCode Plugin (generated bundle)
 * Source: packages/opencode-plugin/src/index.ts
 * Regenerate with: bun scripts/build-opencode-plugin.mjs
 * Do not edit this file by hand; installers copy this single file to ~/.config/opencode/plugins/sybermem.ts.
 */
// @bun
// packages/opencode-plugin/src/followup.ts
import { existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
var SKIP_PREFIXES = [".git/", ".sybermem/", "ADR/", ".claude/", ".opencode/", "node_modules/"];
var SOFT_SKIP = new Set(["CLAUDE.md", "AGENTS.md"]);
var HIGH_SIGNAL_PATTERNS = [/^README(?:\..+)?$/i, /^INSTALL(?:\..+)?$/i, /^CLAUDE\.md$/i, /^AGENTS\.md$/i, /^packages\/claude-skills\/.+\/SKILL\.md$/i, /^\.sybermem\/hooks\//i, /^scripts\/install/i, /^scripts\/update/i, /^docs\/superpowers\/specs\//i];
var HIGH_LEVEL_AREAS = [["skills", /^packages\/claude-skills\//i], ["scripts", /^scripts\//i], ["docs", /^(docs\/|README|INSTALL)/i], ["instructions", /^(CLAUDE\.md|AGENTS\.md)$/i], ["sybermem", /^\.sybermem\//i]];
var RECORD_FILE_THRESHOLD = 5;
var COMMIT_GAP_THRESHOLD = 5;
var THEME_WINDOW_SIZE = 10;
var DIGEST_CLUSTER_THRESHOLD = 2;
var DIGEST_SIGNAL_FILE_FLOOR = 3;
async function getChangedFiles($, cwd) {
  const files = new Set;
  try {
    for (const output of [await $`git diff --name-only`.cwd(cwd).text(), await $`git diff --cached --name-only`.cwd(cwd).text(), await $`git ls-files --others --exclude-standard`.cwd(cwd).text()]) {
      for (const line of output.split(`
`)) {
        const f = line.trim().replace(/\\/g, "/");
        if (f && !SKIP_PREFIXES.some((p) => f.startsWith(p)))
          files.add(f);
      }
    }
  } catch {}
  return [...files];
}
function trailFiles(files) {
  return files.filter((f) => !SOFT_SKIP.has(f)).length > 0 ? [...files] : [];
}
function matchesHighSignal(file) {
  return HIGH_SIGNAL_PATTERNS.some((p) => p.test(file));
}
function detectHighLevelAreas(files) {
  const areas = new Set;
  for (const file of files)
    for (const [name, pattern] of HIGH_LEVEL_AREAS)
      if (pattern.test(file))
        areas.add(name);
  return areas;
}
function slugifyAreas(areas) {
  return [...areas].sort().join("-") || "misc";
}
function classifyFollowup(files, commitsSinceRecord, state) {
  const highSignal = files.filter(matchesHighSignal);
  const areas = detectHighLevelAreas(files);
  const themeKey = slugifyAreas(areas);
  const recentStops = state.theme_recent_stops?.[themeKey] ?? [];
  const presentQualifies = highSignal.length > 0 || areas.size >= 2 || files.length >= DIGEST_SIGNAL_FILE_FLOOR;
  const nudgedAt = state.digest_nudged_at_window_len?.[themeKey];
  if (recentStops.length >= DIGEST_CLUSTER_THRESHOLD && presentQualifies && !(nudgedAt !== undefined && recentStops.length <= nudgedAt)) {
    return { type: "digest", themeKey, message: "SyberMem: recent records around this area may now be enough for a /sybermem-digest if this phase has reached a stable stopping point." };
  }
  const shouldRecord = highSignal.length > 0 || areas.size >= 2 || files.length >= RECORD_FILE_THRESHOLD || commitsSinceRecord >= COMMIT_GAP_THRESHOLD;
  if (shouldRecord && !(state.last_nudge_type === "record" && state.last_theme === themeKey)) {
    const gapNote = commitsSinceRecord >= COMMIT_GAP_THRESHOLD ? ` (${commitsSinceRecord} commits since last record)` : "";
    return { type: "record", themeKey, message: `SyberMem: this change looks important enough for a manual /sybermem-record so the reason and impact are preserved.${gapNote}` };
  }
  return { type: "none", themeKey, message: null };
}
async function countCommitsSinceLastRecord($, root) {
  try {
    let latestDate = "";
    for (const subdir of ["changes", "decisions", "requirements", "bugs"]) {
      const dir = join(root, ".sybermem", subdir);
      if (!existsSync(dir))
        continue;
      const lastFile = readdirSync(dir).filter((f) => f.endsWith(".md")).sort().at(-1);
      const dateMatch = lastFile?.match(/^(\d{4}-\d{2}-\d{2})/);
      if (dateMatch && dateMatch[1] > latestDate)
        latestDate = dateMatch[1];
    }
    if (!latestDate)
      return 0;
    return (await $`git log --oneline --since=${latestDate}`.cwd(root).text()).split(`
`).filter((l) => l.trim()).length;
  } catch {
    return 0;
  }
}
function parseAutoTrailEntry(raw) {
  const parsed = JSON.parse(raw);
  if (typeof parsed !== "object" || parsed === null)
    return null;
  const files = Reflect.get(parsed, "files");
  return Array.isArray(files) ? { files: files.map(String) } : {};
}
function overlapsRecentAutoTrails(root, files) {
  const current = new Set(files);
  if (current.size === 0)
    return false;
  const p = join(root, ".sybermem", ".auto-trail.jsonl");
  const lines = existsSync(p) ? readFileSync(p, "utf-8").split(`
`).filter((line) => line.trim()).slice(-3) : [];
  for (const line of lines) {
    try {
      const entry = parseAutoTrailEntry(line);
      if (!entry)
        continue;
      const trail = new Set((entry.files ?? []).map((f) => String(f).trim()).filter(Boolean));
      let shared = 0;
      for (const f of current)
        if (trail.has(f))
          shared++;
      if (trail.size > 0 && shared / Math.max(current.size, trail.size) >= 0.8)
        return true;
    } catch {}
  }
  return false;
}
function appendAutoTrailJournal(root, date, files, areas, followupHint) {
  const p = join(root, ".sybermem", ".auto-trail.jsonl");
  try {
    const existing = existsSync(p) ? readFileSync(p, "utf-8").split(`
`).filter((l) => l.trim()) : [];
    existing.push(JSON.stringify({ date, files: [...files], areas: [...areas].sort(), followup_hint: followupHint }));
    writeFileSync(p, existing.slice(-200).join(`
`) + `
`, "utf-8");
  } catch {}
}

// packages/opencode-plugin/src/runtime.ts
import { existsSync as existsSync2 } from "fs";
import { join as join2, resolve } from "path";
function resolveRoot(cwd) {
  let current = resolve(cwd);
  while (true) {
    const hasSybermem = existsSync2(join2(current, ".sybermem"));
    const hasSettings = existsSync2(join2(current, ".claude", "settings.json"));
    const hasIndex = existsSync2(join2(current, ".sybermem", "INDEX.md"));
    if (hasSybermem && (hasSettings || hasIndex))
      return current;
    const parent = resolve(current, "..");
    if (parent === current)
      break;
    current = parent;
  }
  return null;
}
function userHome() {
  return process.env.USERPROFILE ?? process.env.HOME ?? null;
}
function resolveSybermemCommand() {
  const home = userHome();
  if (!home)
    return "sybermem";
  const launcher = process.platform === "win32" ? join2(home, ".claude", "sybermem", "cli", "sybermem.cmd") : join2(home, ".claude", "sybermem", "cli", "sybermem");
  return existsSync2(launcher) ? launcher : "sybermem";
}
async function sybermemText($, root, args) {
  const sybermem = resolveSybermemCommand();
  switch (args[0]) {
    case "next-step":
      return $`${sybermem} next-step ${args[1]} ${args[2]}`.cwd(root).text();
    case "habit":
      return $`${sybermem} habit inject ${args[2]} ${args[3]} ${args[4]} ${args[5]}`.cwd(root).text();
    case "context":
      switch (args[1]) {
        case "session":
          return $`${sybermem} context session ${args[2]} ${args[3]}`.cwd(root).text();
        case "recall":
          return $`${sybermem} context recall --query ${args[3]} --format markdown`.cwd(root).text();
        case "habit":
          return $`${sybermem} context habit --context ${args[3]} --delivery ${args[5]} --format ${args[7]}`.cwd(root).text();
      }
      break;
    case "record":
      return $`${sybermem} record intent --prompt ${args[3]} --format ${args[5]}`.cwd(root).text();
  }
  return "";
}
async function digestStatusText($, root) {
  const sybermem = resolveSybermemCommand();
  return $`${sybermem} digest status --format json`.cwd(root).nothrow().text();
}

// packages/opencode-plugin/src/project_state.ts
import { existsSync as existsSync3, readFileSync as readFileSync2 } from "fs";
import { join as join3 } from "path";
function parseIndex(root) {
  const indexPath = join3(root, ".sybermem", "INDEX.md");
  if (!existsSync3(indexPath))
    return null;
  const content = readFileSync2(indexPath, "utf-8");
  const conclusionsMatch = content.match(/## Key Conclusions\s*\n([\s\S]*?)(?=\n---|\n## )/);
  const conclusions = [];
  if (conclusionsMatch) {
    for (const line of conclusionsMatch[1].split(`
`)) {
      const trimmed = line.trim();
      if (trimmed.startsWith("- ["))
        conclusions.push(trimmed);
    }
  }
  const topicMatch = content.match(/## Topic Index\s*\n([\s\S]*?)(?=\n---|\n## |$)/);
  const topicIndex = {};
  if (topicMatch) {
    for (const line of topicMatch[1].split(`
`)) {
      const m = line.match(/^- (\S+):\s*(.+)/);
      if (m)
        topicIndex[m[1]] = m[2].split(",").map((s) => s.trim());
    }
  }
  return { conclusions, topicIndex };
}
function getActivePhase(root) {
  const phasePath = join3(root, ".sybermem", "analysis", "phase-index.md");
  if (!existsSync3(phasePath))
    return null;
  const phases = [...readFileSync2(phasePath, "utf-8").matchAll(/### Phase: (.+)/g)];
  return phases.length === 0 ? null : phases[phases.length - 1][1];
}
function parsePhaseIndex(root) {
  const phasePath = join3(root, ".sybermem", "analysis", "phase-index.md");
  if (!existsSync3(phasePath))
    return { exists: false };
  const content = readFileSync2(phasePath, "utf-8");
  const statusMatch = content.match(/^- status:\s*(.+)/m);
  const phases = [...content.matchAll(/### Phase: (.+)/g)];
  return { exists: true, status: statusMatch ? statusMatch[1].trim() : "unknown", confirmedCount: phases.length, activePhase: getActivePhase(root) };
}
function parseProjectIdentity(root) {
  const projPath = join3(root, ".sybermem", "project.yaml");
  if (!existsSync3(projPath))
    return { exists: false };
  let projectId = null;
  let slug = null;
  for (const raw of readFileSync2(projPath, "utf-8").split(`
`)) {
    const line = raw.trim();
    if (line.startsWith("project_id:"))
      projectId = line.split(":").slice(1).join(":").trim();
    else if (line.startsWith("slug:"))
      slug = line.split(":").slice(1).join(":").trim();
  }
  return { exists: true, projectId, slug };
}
async function detectStaleSignal($, root) {
  const phasePath = join3(root, ".sybermem", "analysis", "phase-index.md");
  if (!existsSync3(phasePath))
    return { stale: false, commitsAhead: 0 };
  const boundaryMatch = readFileSync2(phasePath, "utf-8").match(/^- last_git_boundary:\s*(\S+)/m);
  if (!boundaryMatch)
    return { stale: false, commitsAhead: 0 };
  const boundary = boundaryMatch[1];
  try {
    const head = (await $`git rev-parse HEAD`.cwd(root).text()).trim();
    if (head === boundary)
      return { stale: false, commitsAhead: 0 };
    const countStr = (await $`git rev-list --count ${boundary}..HEAD`.cwd(root).text()).trim();
    const count = Number.parseInt(countStr, 10) || 0;
    return { stale: count >= 3, commitsAhead: count, boundary, head: head.substring(0, 7) };
  } catch {
    return { stale: false, commitsAhead: 0 };
  }
}

// packages/opencode-plugin/src/compaction.ts
function numberField(value, key) {
  if (typeof value !== "object" || value === null)
    return null;
  const field = Reflect.get(value, key);
  return typeof field === "number" ? field : null;
}
function stringField(value, key) {
  if (typeof value !== "object" || value === null)
    return "";
  const field = Reflect.get(value, key);
  return typeof field === "string" ? field.trim() : "";
}
async function buildCompactionContext($, root) {
  const parsed = parseIndex(root);
  if (!parsed || parsed.conclusions.length === 0)
    return null;
  const phaseInfo = parsePhaseIndex(root);
  const identity = parseProjectIdentity(root);
  const stale = await detectStaleSignal($, root);
  let context = "";
  try {
    const manualContext = (await sybermemText($, root, ["context", "session", "--format", "markdown"])).trim();
    if (manualContext.startsWith("## SyberMem Manual Session Context"))
      context += `${manualContext}

`;
  } catch {}
  if (!context)
    context = `## SyberMem Project Memory

`;
  if (identity.exists && identity.slug)
    context += `Project: ${identity.slug} (${identity.projectId ?? "no id"}).

`;
  context += `### Key Conclusions
`;
  for (const c of parsed.conclusions)
    context += `${c}
`;
  if (stale.stale)
    context += `
\u2B50 Heads-up: phase index trails HEAD by ${stale.commitsAhead} commits \u2014 the conclusions above may lag your latest work. Consider /sybermem-phase-analyze before relying on phase context.
`;
  try {
    const staleDigestCount = numberField(JSON.parse(await digestStatusText($, root)), "stale");
    if (staleDigestCount !== null && staleDigestCount > 0)
      context += `
\u2B50 Digest heads-up: ${staleDigestCount} digest(s) are stale \u2014 their source records changed. Run /sybermem-digest to regenerate, or \`sybermem digest status\` to see which sources drifted.
`;
  } catch {}
  if (phaseInfo.exists) {
    context += `
### Phase Index
Status: ${phaseInfo.status}. ${phaseInfo.confirmedCount} confirmed phases.
`;
    if (phaseInfo.activePhase)
      context += `Active phase: ${phaseInfo.activePhase}.
`;
  }
  if (stale.stale)
    context += `
### Stale Signal
Phase-index last git boundary: ${stale.boundary}, current HEAD: ${stale.head} (${stale.commitsAhead} commits ahead).
`;
  if (Object.keys(parsed.topicIndex).length > 0) {
    context += `
### Topic Index
`;
    for (const [topic, records] of Object.entries(parsed.topicIndex))
      context += `- ${topic}: ${records.join(", ")}
`;
  }
  try {
    const rec = JSON.parse(await sybermemText($, root, ["next-step", "--format", "json"]));
    const action = stringField(rec, "action");
    const reason = stringField(rec, "reason");
    if (action)
      context += `
### Recommended Next Step
${action}${reason ? ` \u2014 ${reason}` : ""}
`;
  } catch {}
  try {
    const habitContext = "compaction planning review implementation coding documentation";
    const habitMarkdown = (await sybermemText($, root, ["habit", "inject", "--context", habitContext, "--format", "markdown"])).trim();
    if (habitMarkdown)
      context += `
${habitMarkdown}
`;
  } catch {}
  context += `
### SyberMem Commands
- /sybermem-record \u2014 create a record after meaningful work
- /sybermem-summary \u2014 view current phase status
- /sybermem-digest \u2014 create durable phase digest
`;
  return context.length > 3000 ? `${context.substring(0, 2997)}...` : context;
}

// packages/opencode-plugin/src/state.ts
import { existsSync as existsSync4, readFileSync as readFileSync3, statSync, writeFileSync as writeFileSync2 } from "fs";
import { join as join4 } from "path";
function isObject(value) {
  return typeof value === "object" && value !== null;
}
function parseNudgeState(raw) {
  const parsed = JSON.parse(raw);
  if (!isObject(parsed))
    return {};
  const lastNudge = isObject(parsed.last_nudge) ? parsed.last_nudge : null;
  const state = {};
  if (typeof parsed.lastFingerprint === "string")
    state.lastFingerprint = parsed.lastFingerprint;
  if (typeof parsed.lastNudgeCommitCount === "number")
    state.lastNudgeCommitCount = parsed.lastNudgeCommitCount;
  if (lastNudge && typeof lastNudge.platform === "string" && typeof lastNudge.type === "string" && typeof lastNudge.theme === "string" && typeof lastNudge.date === "string")
    state.last_nudge = { platform: lastNudge.platform, type: lastNudge.type, theme: lastNudge.theme, date: lastNudge.date };
  if (isObject(parsed.theme_recent_stops))
    state.theme_recent_stops = parseStringArrayMap(parsed.theme_recent_stops);
  if (isObject(parsed.digest_nudged_at_window_len))
    state.digest_nudged_at_window_len = parseNumberMap(parsed.digest_nudged_at_window_len);
  if (typeof parsed.last_theme === "string")
    state.last_theme = parsed.last_theme;
  if (typeof parsed.last_nudge_type === "string")
    state.last_nudge_type = parsed.last_nudge_type;
  return state;
}
function parseStringArrayMap(raw) {
  const parsed = {};
  for (const [key, value] of Object.entries(raw))
    if (Array.isArray(value))
      parsed[key] = value.filter((item) => typeof item === "string");
  return parsed;
}
function parseNumberMap(raw) {
  const parsed = {};
  for (const [key, value] of Object.entries(raw))
    if (typeof value === "number")
      parsed[key] = value;
  return parsed;
}
var NUDGE_STATE_FILE = ".nudge-state.json";
var LEGACY_NUDGE_STATE_FILE = ".opencode-nudge-state.json";
var MAX_EXISTING_JSONL_BYTES = 1e6;
function loadNudgeState(root) {
  const p = join4(root, ".sybermem", NUDGE_STATE_FILE);
  if (existsSync4(p)) {
    try {
      return parseNudgeState(readFileSync3(p, "utf-8"));
    } catch {}
  }
  const legacy = join4(root, ".sybermem", LEGACY_NUDGE_STATE_FILE);
  if (existsSync4(legacy)) {
    try {
      const data = parseNudgeState(readFileSync3(legacy, "utf-8"));
      saveNudgeState(root, data);
      return data;
    } catch {}
  }
  return {};
}
function saveNudgeState(root, state) {
  writeFileSync2(join4(root, ".sybermem", NUDGE_STATE_FILE), JSON.stringify(state, null, 2) + `
`, "utf-8");
}
function boundedJsonlAppend(root, fileName, entry, limit) {
  const p = join4(root, ".sybermem", fileName);
  try {
    const existing = existsSync4(p) && statSync(p).size <= MAX_EXISTING_JSONL_BYTES ? readFileSync3(p, "utf-8").split(`
`).filter((line) => line.trim()) : [];
    existing.push(JSON.stringify(entry));
    writeFileSync2(p, existing.slice(-limit).join(`
`) + `
`, "utf-8");
  } catch {}
}

// packages/opencode-plugin/src/recall_debug.ts
var RECORD_ID_RE = /\b(?:change|decision|requirement|bug|digest)-[a-z0-9-]+\b/gi;
var MATCH_CLASS_RE = /\b(record-id|relation|topic|keyword|semantic)\b/gi;
function uniqueMatches(text, pattern) {
  return [...new Set([...text.matchAll(pattern)].map((m) => m[0].toLowerCase()))].slice(0, 20);
}
function buildRecallDebugEntry(packets, timestamp = new Date().toISOString()) {
  const recallPacket = packets.find((packet) => packet.trim().startsWith("## SyberMem Recall Hints")) ?? "";
  if (!recallPacket)
    return { source: "opencode-chat-message", timestamp, event: "abstain", record_ids: [], match_classes: [], reason: "no-high-signal-recall" };
  return { source: "opencode-chat-message", timestamp, event: "inject", record_ids: uniqueMatches(recallPacket, RECORD_ID_RE), match_classes: uniqueMatches(recallPacket, MATCH_CLASS_RE), reason: "high-signal-recall" };
}
function appendRecallDebug(root, packets, timestamp) {
  boundedJsonlAppend(root, ".recall-debug.jsonl", buildRecallDebugEntry(packets, timestamp), 200);
}

// packages/opencode-plugin/src/record_intent.ts
import { writeFileSync as writeFileSync3 } from "fs";
import { join as join5 } from "path";
var BLOCKED_PATTERN = /(password\s*=|token\s*=|secret\s*=|bearer\s+[a-z0-9._-]+|api[_ -]?key\s*=|begin\s+(?:rsa\s+)?private\s+key|ignore\s+(?:all\s+)?previous|system\s+prompt|developer\s+message|<\/?(?:system|developer|tool)[^>]*>|\/sybermem-record\s+--|\u4E0D\u8981.{0,8}(\u8BB0\u5F55|\u6C89\u6DC0)|do\s+not\s+record|don'?t\s+record)/i;
var RULES = [
  { classification: "bug", id: "bug-fix", pattern: /(bug|fix|crash|regression|\u4FEE\u590D|\u7F3A\u9677|\u95EE\u9898)/i, reason: "explicit bug record request" },
  { classification: "decision", id: "decision", pattern: /(decision|architecture decision|adr|\u51B3\u5B9A|\u51B3\u7B56)/i, reason: "explicit decision record request" },
  { classification: "requirement", id: "requirement", pattern: /(requirement|\u9700\u6C42|must|\u5FC5\u987B|should)/i, reason: "explicit requirement record request" },
  { classification: "change", id: "change", pattern: /(record|\u8BB0\u5F55|\u6C89\u6DC0|\u5B9E\u73B0|\u5B8C\u6210|change)/i, reason: "explicit change record request" }
];
function classifyRecordIntent(text, createdAt = new Date().toISOString()) {
  if (!/(record|\u8BB0\u5F55|\u6C89\u6DC0)/i.test(text) || isBlockedPrompt(text))
    return null;
  for (const rule of RULES) {
    if (rule.pattern.test(text)) {
      return { record_intent: true, classification: rule.classification, action: "/sybermem-record", reason: rule.reason, source: "opencode-chat-message", created_at: createdAt, matched_pattern: rule.id, phrase: "" };
    }
  }
  return null;
}
function isBlockedPrompt(text) {
  return BLOCKED_PATTERN.test(text);
}
function isRecordIntentType(classification) {
  return classification === "change" || classification === "decision" || classification === "requirement" || classification === "bug";
}
function fromCoreCandidate(candidate, createdAt) {
  if (!isRecordIntentType(candidate.classification))
    return null;
  return {
    record_intent: true,
    classification: candidate.classification,
    action: "/sybermem-record",
    reason: typeof candidate.reason === "string" ? candidate.reason : "bounded core classifier match",
    source: "opencode-chat-message",
    created_at: createdAt,
    matched_pattern: "core-classifier",
    phrase: ""
  };
}
async function classifyWithCli($, root, text, createdAt) {
  try {
    const candidate = JSON.parse(await sybermemText($, root, ["record", "intent", "--prompt", text, "--format", "json"]));
    if (typeof candidate !== "object" || candidate === null)
      return null;
    const classification = Reflect.get(candidate, "classification");
    const reason = Reflect.get(candidate, "reason");
    if (typeof classification !== "string")
      return null;
    return fromCoreCandidate({ classification, reason: typeof reason === "string" ? reason : undefined }, createdAt);
  } catch {
    return null;
  }
}
async function captureRecordIntentWithCli($, root, text, createdAt = new Date().toISOString()) {
  if (isBlockedPrompt(text))
    return false;
  const metadata = await classifyWithCli($, root, text, createdAt) ?? classifyRecordIntent(text, createdAt);
  if (!metadata)
    return false;
  try {
    writeFileSync3(join5(root, ".sybermem", ".record-intent.json"), JSON.stringify(metadata, null, 2) + `
`, "utf-8");
    return true;
  } catch {
    return false;
  }
}

// packages/opencode-plugin/src/prompt_context.ts
var RECALL_STASH = new Map;
function extractPromptText(output) {
  return (output.parts ?? []).filter((p) => p.type === "text").map((p) => p.text ?? "").join(" ").trim();
}
function appendPromptPacket(packets, raw, heading) {
  const trimmed = raw.trim();
  if (trimmed.startsWith(heading))
    packets.push(trimmed);
}
async function collectPromptPackets($, root, text) {
  const packets = [];
  try {
    const raw = await sybermemText($, root, ["context", "recall", "--query", text, "--format", "markdown"]);
    appendPromptPacket(packets, raw, "## SyberMem Recall Hints");
  } catch {}
  try {
    const raw = await sybermemText($, root, ["context", "habit", "--context", text, "--delivery", "prompt-time", "--format", "markdown"]);
    appendPromptPacket(packets, raw, "## User Habit Reminder");
  } catch {}
  return packets;
}
function stashPromptPackets(sessionID, packets) {
  if (packets.length > 0)
    RECALL_STASH.set(sessionID, packets);
  else
    RECALL_STASH.delete(sessionID);
}
var NO_INJECTION = { injected: false, recallCount: 0, habitCount: 0, habitCandidate: false };
function classifyPackets(packets) {
  if (packets.length === 0)
    return NO_INJECTION;
  let recallCount = 0;
  let habitCount = 0;
  let habitCandidate = false;
  for (const packet of packets) {
    const trimmed = packet.trim();
    if (trimmed.startsWith("## SyberMem Recall Hints")) {
      recallCount += countBullets(trimmed);
    } else if (trimmed.startsWith("## User Habit Reminder")) {
      const habitLines = trimmed.split(`
`).filter((line) => line.startsWith("- [habit-"));
      habitCount += habitLines.length;
      if (habitLines.length === 0)
        habitCandidate = true;
    }
  }
  return { injected: recallCount > 0 || habitCount > 0 || habitCandidate, recallCount, habitCount, habitCandidate };
}
function countBullets(packet) {
  return packet.split(`
`).filter((line) => /^-\s/.test(line.trim())).length;
}
function injectStashedPromptPackets(sessionID, output) {
  const packets = RECALL_STASH.get(sessionID);
  RECALL_STASH.delete(sessionID);
  if (!packets || packets.length === 0)
    return NO_INJECTION;
  const hints = packets.join(`

`);
  if (output.system && output.system.length > 0)
    output.system[0] = `${hints}

${output.system[0]}`;
  else
    output.system = [hints, ...output.system ?? []];
  return classifyPackets(packets);
}

// packages/opencode-plugin/src/plugin.ts
async function showToast(client, message) {
  try {
    await client.tui.showToast({ body: { message, variant: "info" } });
  } catch {}
}
var LAST_TOAST = new Map;
var TOAST_COOLDOWN_MS = 30000;
function throttledToast(client, key, message) {
  const now = Date.now();
  const last = LAST_TOAST.get(key) ?? 0;
  if (now - last < TOAST_COOLDOWN_MS)
    return;
  LAST_TOAST.set(key, now);
  showToast(client, message);
}
function describeInjection(summary) {
  const parts = [];
  if (summary.recallCount > 0)
    parts.push(`${summary.recallCount} recall hint${summary.recallCount === 1 ? "" : "s"}`);
  if (summary.habitCount > 0)
    parts.push(`${summary.habitCount} habit reminder${summary.habitCount === 1 ? "" : "s"}`);
  if (parts.length === 0)
    return "";
  return parts.join(" + ");
}
async function handleSessionCreated(args, root) {
  const parsed = parseIndex(root);
  if (!parsed || parsed.conclusions.length === 0)
    return;
  const stale = await detectStaleSignal(args.$, root);
  const staleNote = stale.stale ? ` (phase-index ${stale.commitsAhead} commits behind)` : "";
  const commitsSinceRecord = await countCommitsSinceLastRecord(args.$, root);
  const recordNote = commitsSinceRecord >= 3 ? `. ${commitsSinceRecord} commits since last record \u2014 consider /sybermem-record` : "";
  const ahaMarker = stale.stale || commitsSinceRecord >= 3 ? "\u2B50 " : "";
  await args.client.tui.showToast({ body: { message: `${ahaMarker}SyberMem: loaded ${parsed.conclusions.length} key conclusions${staleNote}${recordNote}`, variant: "info" } });
}
async function handleSessionIdle(args, root) {
  const trail = trailFiles(await getChangedFiles(args.$, root));
  if (trail.length === 0)
    return;
  const fingerprint = JSON.stringify(trail);
  const state = loadNudgeState(root);
  if (state.lastFingerprint === fingerprint)
    return;
  if (overlapsRecentAutoTrails(root, trail)) {
    saveNudgeState(root, { ...state, lastFingerprint: fingerprint });
    return;
  }
  const commitsSince = await countCommitsSinceLastRecord(args.$, root);
  const followup = classifyFollowup(trail, commitsSince, state);
  const today = new Date().toISOString().split("T")[0];
  appendAutoTrailJournal(root, today, trail, detectHighLevelAreas(trail), followup.type);
  const windows = { ...state.theme_recent_stops ?? {} };
  windows[followup.themeKey] = [...windows[followup.themeKey] ?? [], today].slice(-THEME_WINDOW_SIZE);
  const digestGuard = { ...state.digest_nudged_at_window_len ?? {} };
  if (followup.type === "digest")
    digestGuard[followup.themeKey] = windows[followup.themeKey].length;
  saveNudgeState(root, { ...state, lastFingerprint: fingerprint, lastNudgeCommitCount: commitsSince, theme_recent_stops: windows, digest_nudged_at_window_len: digestGuard, last_theme: followup.themeKey, last_nudge_type: followup.type, last_nudge: followup.type === "none" ? state.last_nudge : { platform: "opencode", type: followup.type, theme: followup.themeKey, date: today } });
  if (followup.type !== "none")
    await args.client.tui.showToast({ body: { message: followup.message ?? "SyberMem: consider recording this work.", variant: "info" } });
}
var SyberMemPlugin = async ({ $, directory, client }) => {
  const args = { $, directory, client };
  const root = resolveRoot(directory);
  return {
    event: async ({ event }) => {
      if (!root)
        return;
      if (event.type === "session.created")
        await handleSessionCreated(args, root);
      if (event.type === "session.idle")
        await handleSessionIdle(args, root);
    },
    "chat.message": async ({ sessionID }, output) => {
      if (!root)
        return;
      const text = extractPromptText(output);
      if (!text)
        return;
      await captureRecordIntentWithCli(args.$, root, text);
      const packets = await collectPromptPackets(args.$, root, text);
      appendRecallDebug(root, packets);
      stashPromptPackets(sessionID, packets);
      const summary = classifyPackets(packets);
      if (summary.habitCandidate) {
        throttledToast(args.client, "habit-candidate", "\uD83D\uDCA1 Detected a reusable preference \u2014 save it with /sybermem-habit");
      }
    },
    "experimental.chat.system.transform": async ({ sessionID }, output) => {
      if (!root)
        return;
      const summary = injectStashedPromptPackets(sessionID ?? "", output);
      if (summary.injected && !summary.habitCandidate) {
        throttledToast(args.client, "recall-injected", `\u2B50 SyberMem: injected ${describeInjection(summary)} into this prompt`);
      }
    },
    "experimental.session.compacting": async (_input, output) => {
      if (!root)
        return;
      const context = await buildCompactionContext(args.$, root);
      if (context)
        output.context.push(context);
    }
  };
};
export {
  SyberMemPlugin
};
