/**
 * SyberMem OpenCode Plugin (generated bundle)
 * Source: packages/opencode-plugin/src/tui.ts
 * Regenerate with: bun scripts/build-opencode-plugin.mjs --tui
 * Do not edit this file by hand; deploy as the TUI companion to the server bundle.
 */
// @bun
// packages/opencode-plugin/src/v2_feedback.ts
import { resolve } from "path";
var text = { type: "string" };
var integer = { type: "integer", minimum: 0 };
var summarySchema = { type: "object", additionalProperties: false, required: ["epoch", "sessionID", "sequence", "messageID", "message", "totalItems", "totalChars"], properties: {
  epoch: text,
  sessionID: text,
  sequence: integer,
  messageID: text,
  message: text,
  totalItems: integer,
  totalChars: integer
} };
var feedbackRpc = {
  id: "sybermem-feedback",
  methods: { status: {
    input: { type: "object", additionalProperties: false, required: ["sessionID"], properties: { sessionID: text } },
    output: { type: "object", additionalProperties: false, required: ["epoch", "summary"], properties: { epoch: text, summary: { anyOf: [summarySchema, { type: "null" }] } } }
  } },
  events: { notice: { schema: { type: "object", additionalProperties: false, required: ["epoch", "sessionID", "sequence", "kind", "message", "messageID", "totalItems", "totalChars"], properties: {
    epoch: text,
    sessionID: text,
    sequence: integer,
    kind: { type: "string", enum: ["summary", "advisory"] },
    message: text,
    messageID: text,
    totalItems: integer,
    totalChars: integer
  } } } }
};
function sameLocation(left, right) {
  return !!left && !!right && resolve(left).toLowerCase() === resolve(right).toLowerCase();
}
function feedbackGate(directory, current, show) {
  const seen = new Map;
  const summaries = new Map;
  const candidates = new Map;
  let candidateVersion = 0;
  const selected = (sessionID) => {
    const route = current();
    return route.type === "session" && route.sessionID === sessionID;
  };
  const advance = (sessionID, epoch) => {
    const state = seen.get(sessionID);
    if (state?.retired.has(epoch))
      return;
    if (state?.epoch === epoch)
      return state;
    const next = { epoch, sequence: 0, revision: (state?.revision ?? 0) + 1, retired: new Set(state?.retired) };
    if (state)
      next.retired.add(state.epoch);
    seen.set(sessionID, next);
    return next;
  };
  return {
    revision(sessionID) {
      return seen.get(sessionID)?.revision ?? 0;
    },
    challenge(sessionID) {
      return candidates.get(sessionID)?.version ?? 0;
    },
    accept(event) {
      const item = event.data;
      if (!sameLocation(event.location?.directory, directory) || !item || !item.sessionID || !item.epoch || !Number.isSafeInteger(item.sequence) || item.sequence < 1 || !selected(item.sessionID))
        return;
      const currentState = seen.get(item.sessionID);
      if (currentState?.retired.has(item.epoch))
        return;
      if (!currentState || currentState.epoch !== item.epoch) {
        const previous = candidates.get(item.sessionID);
        if (!previous || previous.notice.epoch !== item.epoch || item.sequence > previous.notice.sequence) {
          candidates.set(item.sessionID, { notice: item, version: ++candidateVersion });
        }
        return true;
      }
      const state = currentState;
      if (item.sequence <= state.sequence)
        return;
      state.sequence = item.sequence;
      state.revision++;
      if (item.kind === "summary" && item.messageID) {
        const ids = summaries.get(item.sessionID) ?? new Set;
        if (ids.has(item.messageID))
          return;
        ids.add(item.messageID);
        summaries.set(item.sessionID, ids);
      }
      show(item);
    },
    restore(status, sessionID, requestedRevision = this.revision(sessionID), requestedChallenge = this.challenge(sessionID)) {
      if (!status?.epoch || !selected(sessionID) || requestedRevision !== this.revision(sessionID))
        return;
      if (status.summary && (status.summary.sessionID !== sessionID || status.summary.epoch !== status.epoch))
        return;
      const state = advance(sessionID, status.epoch);
      if (!state)
        return;
      const candidate = candidates.get(sessionID);
      if (status.summary && !(candidate?.notice.epoch === status.epoch && candidate.notice.sequence > status.summary.sequence)) {
        this.accept({ location: { directory }, data: { ...status.summary, kind: "summary" } });
      }
      if (candidate && candidate.notice.epoch === status.epoch) {
        candidates.delete(sessionID);
        this.accept({ location: { directory }, data: candidate.notice });
      } else if (candidate && candidate.version <= requestedChallenge) {
        state.retired.add(candidate.notice.epoch);
        candidates.delete(sessionID);
      }
    },
    clear() {
      seen.clear();
      summaries.clear();
      candidates.clear();
    }
  };
}

// packages/opencode-plugin/src/tui.ts
function setupSyberMemTui(ctx, refreshMs = 2000) {
  const directory = ctx.location?.directory;
  if (!directory)
    return () => {};
  const rpc = ctx.client.rpc(feedbackRpc);
  let stopped = false;
  let selected;
  let ticks = 0;
  let generation = 0;
  let pending;
  const active = (sessionID) => sameLocation(ctx.location?.directory, directory) && ctx.ui.router.current().type === "session" && ctx.ui.router.current().sessionID === sessionID;
  const gate = feedbackGate(directory, () => ctx.ui.router.current(), (notice) => {
    if (!stopped && active(notice.sessionID))
      ctx.ui.toast.show({ title: "SyberMem", message: notice.message, variant: "info", duration: notice.kind === "summary" ? 3500 : 5000, sessionID: notice.sessionID });
  });
  const refresh = (force = false) => {
    if (stopped)
      return;
    const route = ctx.ui.router.current();
    const sessionID = sameLocation(ctx.location?.directory, directory) && route.type === "session" ? route.sessionID : undefined;
    if (sessionID !== selected) {
      selected = sessionID;
      ++generation;
      pending = undefined;
      force = true;
    }
    if (!force)
      return;
    if (!sessionID)
      return;
    if (pending) {
      pending.queued = true;
      return;
    }
    const task = { sessionID, generation, queued: false };
    pending = task;
    const revision = gate.revision(sessionID);
    const challenge = gate.challenge(sessionID);
    Promise.resolve().then(() => rpc.status({ sessionID })).then((status) => {
      if (!stopped && task === pending && task.generation === generation && active(sessionID))
        gate.restore(status, sessionID, revision, challenge);
    }).catch(() => {}).finally(() => {
      if (task !== pending)
        return;
      pending = undefined;
      if (task.queued && !stopped)
        refresh(true);
    });
  };
  const off = rpc.events.on("notice", (event) => {
    refresh();
    if (!stopped && sameLocation(ctx.location?.directory, directory) && gate.accept(event))
      refresh(true);
  });
  const offData = ctx.data?.listen(() => refresh(true));
  refresh();
  const timer = setInterval(() => {
    refresh(++ticks % 5 === 0);
  }, refreshMs);
  return () => {
    if (stopped)
      return;
    stopped = true;
    ++generation;
    pending = undefined;
    clearInterval(timer);
    try {
      offData?.();
    } catch {}
    try {
      off();
    } catch {}
    gate.clear();
  };
}
var tui_default = { id: "sybermem-tui", setup: setupSyberMemTui };
export {
  setupSyberMemTui,
  tui_default as default
};
